// Auto-generated by scripts/updateData.js — last update: 2026-05-19
// SK: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataSK: CrossSellData = {
  "totalOrders": 1024,
  "multiItemOrders": 841,
  "pairs": [
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 192,
      "pct": 18.75
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 132,
      "pct": 12.89
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 129,
      "pct": 12.6
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 109,
      "pct": 10.64
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 99,
      "pct": 9.67
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 93,
      "pct": 9.08
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 81,
      "pct": 7.91
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 81,
      "pct": 7.91
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 80,
      "pct": 7.81
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 73,
      "pct": 7.13
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 63,
      "pct": 6.15
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 60,
      "pct": 5.86
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 58,
      "pct": 5.66
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 58,
      "pct": 5.66
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 57,
      "pct": 5.57
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 56,
      "pct": 5.47
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 55,
      "pct": 5.37
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 55,
      "pct": 5.37
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 53,
      "pct": 5.18
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 53,
      "pct": 5.18
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 53,
      "pct": 5.18
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 50,
      "pct": 4.88
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 49,
      "pct": 4.79
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 48,
      "pct": 4.69
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 46,
      "pct": 4.49
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 46,
      "pct": 4.49
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v arašidovom oleji 115 g",
      "count": 44,
      "pct": 4.3
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Nátierka z tuniaka s parmezánom 60 g",
      "count": 44,
      "pct": 4.3
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 43,
      "pct": 4.2
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 43,
      "pct": 4.2
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 43,
      "pct": 4.2
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 42,
      "pct": 4.1
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 42,
      "pct": 4.1
    },
    {
      "productA": "Sardinky v olivovom oleji s paradajkami 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 42,
      "pct": 4.1
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 41,
      "pct": 4
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 41,
      "pct": 4
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 40,
      "pct": 3.91
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 40,
      "pct": 3.91
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 40,
      "pct": 3.91
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 39,
      "pct": 3.81
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 39,
      "pct": 3.81
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 39,
      "pct": 3.81
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 39,
      "pct": 3.81
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 39,
      "pct": 3.81
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 39,
      "pct": 3.81
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 39,
      "pct": 3.81
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 38,
      "pct": 3.71
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 38,
      "pct": 3.71
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 37,
      "pct": 3.61
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 37,
      "pct": 3.61
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 36,
      "pct": 3.52
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 36,
      "pct": 3.52
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 35,
      "pct": 3.42
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 35,
      "pct": 3.42
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 35,
      "pct": 3.42
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 35,
      "pct": 3.42
    },
    {
      "productA": "Osobný odber",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 35,
      "pct": 3.42
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 34,
      "pct": 3.32
    },
    {
      "productA": "Rillettes z tresky so sečuánskym korením 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 34,
      "pct": 3.32
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 34,
      "pct": 3.32
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 33,
      "pct": 3.22
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 33,
      "pct": 3.22
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "count": 33,
      "pct": 3.22
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 33,
      "pct": 3.22
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 33,
      "pct": 3.22
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Nátierka zo sardiniek s whisky 60 g",
      "count": 33,
      "pct": 3.22
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 32,
      "pct": 3.13
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 32,
      "pct": 3.13
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky marinované vínom Muscadet 115 g",
      "count": 32,
      "pct": 3.13
    },
    {
      "productA": "Sardinky v slnečnicovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 32,
      "pct": 3.13
    },
    {
      "productA": "Nátierka zo sardiniek s whisky 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 32,
      "pct": 3.13
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky Luzienne 115 g",
      "count": 31,
      "pct": 3.03
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 31,
      "pct": 3.03
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 31,
      "pct": 3.03
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 31,
      "pct": 3.03
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 31,
      "pct": 3.03
    },
    {
      "productA": "Penová nátierka z homára s koňakom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 31,
      "pct": 3.03
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 30,
      "pct": 2.93
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 30,
      "pct": 2.93
    },
    {
      "productA": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 30,
      "pct": 2.93
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 30,
      "pct": 2.93
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 30,
      "pct": 2.93
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 30,
      "pct": 2.93
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 30,
      "pct": 2.93
    },
    {
      "productA": "Penová nátierka z homára s koňakom 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 30,
      "pct": 2.93
    },
    {
      "productA": "Rillettes z tresky so sečuánskym korením 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 30,
      "pct": 2.93
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovou tapenádou 115 g",
      "count": 29,
      "pct": 2.83
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Nátierka z tuniaka s parmezánom 60 g",
      "count": 29,
      "pct": 2.83
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 28,
      "pct": 2.73
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 28,
      "pct": 2.73
    },
    {
      "productA": "Sardinky v olivovom oleji s paradajkami 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 28,
      "pct": 2.73
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 28,
      "pct": 2.73
    },
    {
      "productA": "Makrela s omáčkou z bergamotu a kôpru 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 28,
      "pct": 2.73
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Makrela vo víne s aromatickým korením 118 g",
      "count": 28,
      "pct": 2.73
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 28,
      "pct": 2.73
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 28,
      "pct": 2.73
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 28,
      "pct": 2.73
    },
    {
      "productA": "Makrela s paradajkami 112,5 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 28,
      "pct": 2.73
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 28,
      "pct": 2.73
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 28,
      "pct": 2.73
    }
  ]
};
