// Auto-generated by scripts/updateData.js — last update: 2026-05-19
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 47,
    "totalRevenue": 466.97,
    "totalOrders": 1,
    "avgRevenue": 9.94,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 47,
    "totalRevenue": 733.93,
    "totalOrders": 1,
    "avgRevenue": 15.62,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 47,
    "totalRevenue": 2873.21,
    "totalOrders": 3,
    "avgRevenue": 61.13,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 47,
    "totalRevenue": 5193.13,
    "totalOrders": 7,
    "avgRevenue": 110.49,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 47,
    "totalRevenue": 7167.07,
    "totalOrders": 7,
    "avgRevenue": 152.49,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 47,
    "totalRevenue": 13599.85,
    "totalOrders": 11,
    "avgRevenue": 289.36,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 47,
    "totalRevenue": 10793.38,
    "totalOrders": 11,
    "avgRevenue": 229.65,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 47,
    "totalRevenue": 15090.46,
    "totalOrders": 12,
    "avgRevenue": 321.07,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 47,
    "totalRevenue": 15026.33,
    "totalOrders": 14,
    "avgRevenue": 319.71,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 47,
    "totalRevenue": 35221.75,
    "totalOrders": 25,
    "avgRevenue": 749.4,
    "avgOrders": 0.53
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 47,
    "totalRevenue": 36395.48,
    "totalOrders": 19,
    "avgRevenue": 774.37,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 47,
    "totalRevenue": 11109.72,
    "totalOrders": 9,
    "avgRevenue": 236.38,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 47,
    "totalRevenue": 11185.8,
    "totalOrders": 15,
    "avgRevenue": 238,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 47,
    "totalRevenue": 14147.86,
    "totalOrders": 17,
    "avgRevenue": 301.02,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 47,
    "totalRevenue": 29121.83,
    "totalOrders": 20,
    "avgRevenue": 619.61,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 47,
    "totalRevenue": 30300.26,
    "totalOrders": 23,
    "avgRevenue": 644.69,
    "avgOrders": 0.49
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 47,
    "totalRevenue": 29385.49,
    "totalOrders": 20,
    "avgRevenue": 625.22,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 47,
    "totalRevenue": 17370.03,
    "totalOrders": 14,
    "avgRevenue": 369.58,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 47,
    "totalRevenue": 18924.66,
    "totalOrders": 15,
    "avgRevenue": 402.65,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 47,
    "totalRevenue": 16487.8,
    "totalOrders": 14,
    "avgRevenue": 350.8,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 48,
    "totalRevenue": 6242.89,
    "totalOrders": 3,
    "avgRevenue": 130.06,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 48,
    "totalRevenue": 4152.51,
    "totalOrders": 3,
    "avgRevenue": 86.51,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 48,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 48,
    "totalRevenue": 2005.36,
    "totalOrders": 1,
    "avgRevenue": 41.78,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 48,
    "totalRevenue": 993.75,
    "totalOrders": 1,
    "avgRevenue": 20.7,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 48,
    "totalRevenue": 1203.58,
    "totalOrders": 1,
    "avgRevenue": 25.07,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 48,
    "totalRevenue": 5562.5,
    "totalOrders": 4,
    "avgRevenue": 115.89,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 48,
    "totalRevenue": 6674.13,
    "totalOrders": 6,
    "avgRevenue": 139.04,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 48,
    "totalRevenue": 10383.8,
    "totalOrders": 8,
    "avgRevenue": 216.33,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 48,
    "totalRevenue": 8221.78,
    "totalOrders": 5,
    "avgRevenue": 171.29,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 48,
    "totalRevenue": 22212.98,
    "totalOrders": 20,
    "avgRevenue": 462.77,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 48,
    "totalRevenue": 14615.46,
    "totalOrders": 12,
    "avgRevenue": 304.49,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 48,
    "totalRevenue": 15765.41,
    "totalOrders": 12,
    "avgRevenue": 328.45,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 48,
    "totalRevenue": 10790.72,
    "totalOrders": 12,
    "avgRevenue": 224.81,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 48,
    "totalRevenue": 8592.88,
    "totalOrders": 10,
    "avgRevenue": 179.02,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 48,
    "totalRevenue": 19931.09,
    "totalOrders": 15,
    "avgRevenue": 415.23,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 48,
    "totalRevenue": 15870.81,
    "totalOrders": 15,
    "avgRevenue": 330.64,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 48,
    "totalRevenue": 15790.15,
    "totalOrders": 10,
    "avgRevenue": 328.96,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 48,
    "totalRevenue": 20164.49,
    "totalOrders": 18,
    "avgRevenue": 420.09,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 48,
    "totalRevenue": 36895.37,
    "totalOrders": 23,
    "avgRevenue": 768.65,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 48,
    "totalRevenue": 12669.86,
    "totalOrders": 11,
    "avgRevenue": 263.96,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 48,
    "totalRevenue": 36397.75,
    "totalOrders": 28,
    "avgRevenue": 758.29,
    "avgOrders": 0.58
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 48,
    "totalRevenue": 24542.76,
    "totalOrders": 18,
    "avgRevenue": 511.31,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 48,
    "totalRevenue": 14773.32,
    "totalOrders": 12,
    "avgRevenue": 307.78,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 46,
    "totalRevenue": 5236.52,
    "totalOrders": 6,
    "avgRevenue": 113.84,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 46,
    "totalRevenue": 5373.27,
    "totalOrders": 4,
    "avgRevenue": 116.81,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 46,
    "totalRevenue": 319.65,
    "totalOrders": 1,
    "avgRevenue": 6.95,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 46,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 46,
    "totalRevenue": 2810.72,
    "totalOrders": 2,
    "avgRevenue": 61.1,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 46,
    "totalRevenue": 1832.14,
    "totalOrders": 1,
    "avgRevenue": 39.83,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 46,
    "totalRevenue": 4955.25,
    "totalOrders": 5,
    "avgRevenue": 107.72,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 46,
    "totalRevenue": 7070.49,
    "totalOrders": 8,
    "avgRevenue": 153.71,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 46,
    "totalRevenue": 6833.83,
    "totalOrders": 7,
    "avgRevenue": 148.56,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 46,
    "totalRevenue": 17367.24,
    "totalOrders": 15,
    "avgRevenue": 377.55,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 46,
    "totalRevenue": 23162.18,
    "totalOrders": 17,
    "avgRevenue": 503.53,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 46,
    "totalRevenue": 25598.43,
    "totalOrders": 22,
    "avgRevenue": 556.49,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 46,
    "totalRevenue": 18986,
    "totalOrders": 15,
    "avgRevenue": 412.74,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 46,
    "totalRevenue": 19392.08,
    "totalOrders": 14,
    "avgRevenue": 421.57,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 46,
    "totalRevenue": 17670.28,
    "totalOrders": 14,
    "avgRevenue": 384.14,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 46,
    "totalRevenue": 14847.18,
    "totalOrders": 11,
    "avgRevenue": 322.76,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 46,
    "totalRevenue": 14100.28,
    "totalOrders": 9,
    "avgRevenue": 306.53,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 46,
    "totalRevenue": 18943.34,
    "totalOrders": 14,
    "avgRevenue": 411.81,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 46,
    "totalRevenue": 33856.07,
    "totalOrders": 16,
    "avgRevenue": 736,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 46,
    "totalRevenue": 31913.42,
    "totalOrders": 26,
    "avgRevenue": 693.77,
    "avgOrders": 0.57
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 46,
    "totalRevenue": 24455.93,
    "totalOrders": 22,
    "avgRevenue": 531.65,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 46,
    "totalRevenue": 23384.21,
    "totalOrders": 24,
    "avgRevenue": 508.35,
    "avgOrders": 0.52
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 46,
    "totalRevenue": 25440.49,
    "totalOrders": 23,
    "avgRevenue": 553.05,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 46,
    "totalRevenue": 18718.66,
    "totalOrders": 14,
    "avgRevenue": 406.93,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 47,
    "totalRevenue": 7306.98,
    "totalOrders": 7,
    "avgRevenue": 155.47,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 47,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 47,
    "totalRevenue": 1428.94,
    "totalOrders": 2,
    "avgRevenue": 30.4,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 47,
    "totalRevenue": 1029.47,
    "totalOrders": 1,
    "avgRevenue": 21.9,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 47,
    "totalRevenue": 1044.63,
    "totalOrders": 1,
    "avgRevenue": 22.23,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 47,
    "totalRevenue": 2121.42,
    "totalOrders": 1,
    "avgRevenue": 45.14,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 47,
    "totalRevenue": 2053.57,
    "totalOrders": 1,
    "avgRevenue": 43.69,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 47,
    "totalRevenue": 11480.15,
    "totalOrders": 6,
    "avgRevenue": 244.26,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 47,
    "totalRevenue": 12064.52,
    "totalOrders": 11,
    "avgRevenue": 256.69,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 47,
    "totalRevenue": 13067.7,
    "totalOrders": 10,
    "avgRevenue": 278.04,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 47,
    "totalRevenue": 15235.24,
    "totalOrders": 16,
    "avgRevenue": 324.15,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 47,
    "totalRevenue": 12322.18,
    "totalOrders": 10,
    "avgRevenue": 262.17,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 47,
    "totalRevenue": 11590.57,
    "totalOrders": 10,
    "avgRevenue": 246.61,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 47,
    "totalRevenue": 9738.5,
    "totalOrders": 10,
    "avgRevenue": 207.2,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 47,
    "totalRevenue": 12186.13,
    "totalOrders": 12,
    "avgRevenue": 259.28,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 47,
    "totalRevenue": 20874.1,
    "totalOrders": 14,
    "avgRevenue": 444.13,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 47,
    "totalRevenue": 14257.47,
    "totalOrders": 11,
    "avgRevenue": 303.35,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 47,
    "totalRevenue": 15859.25,
    "totalOrders": 11,
    "avgRevenue": 337.43,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 47,
    "totalRevenue": 11861.6,
    "totalOrders": 10,
    "avgRevenue": 252.37,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 47,
    "totalRevenue": 19890.23,
    "totalOrders": 14,
    "avgRevenue": 423.2,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 47,
    "totalRevenue": 23518.79,
    "totalOrders": 22,
    "avgRevenue": 500.4,
    "avgOrders": 0.47
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 47,
    "totalRevenue": 19482.23,
    "totalOrders": 15,
    "avgRevenue": 414.52,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 47,
    "totalRevenue": 22205.23,
    "totalOrders": 19,
    "avgRevenue": 472.45,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 47,
    "totalRevenue": 10214,
    "totalOrders": 10,
    "avgRevenue": 217.32,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 49,
    "totalRevenue": 6221.29,
    "totalOrders": 3,
    "avgRevenue": 126.97,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 49,
    "totalRevenue": 6173.87,
    "totalOrders": 2,
    "avgRevenue": 126,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 49,
    "totalRevenue": 5247.31,
    "totalOrders": 3,
    "avgRevenue": 107.09,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 49,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 49,
    "totalRevenue": 1110.75,
    "totalOrders": 1,
    "avgRevenue": 22.67,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 49,
    "totalRevenue": 2854.45,
    "totalOrders": 2,
    "avgRevenue": 58.25,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 49,
    "totalRevenue": 4947.14,
    "totalOrders": 3,
    "avgRevenue": 100.96,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 49,
    "totalRevenue": 7095.22,
    "totalOrders": 6,
    "avgRevenue": 144.8,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 49,
    "totalRevenue": 8504.23,
    "totalOrders": 6,
    "avgRevenue": 173.56,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 49,
    "totalRevenue": 14442.89,
    "totalOrders": 11,
    "avgRevenue": 294.75,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 49,
    "totalRevenue": 17299.89,
    "totalOrders": 15,
    "avgRevenue": 353.06,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 49,
    "totalRevenue": 21590.22,
    "totalOrders": 18,
    "avgRevenue": 440.62,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 49,
    "totalRevenue": 10213.22,
    "totalOrders": 9,
    "avgRevenue": 208.43,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 49,
    "totalRevenue": 10140.61,
    "totalOrders": 7,
    "avgRevenue": 206.95,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 49,
    "totalRevenue": 27715.11,
    "totalOrders": 19,
    "avgRevenue": 565.61,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 49,
    "totalRevenue": 14199.02,
    "totalOrders": 11,
    "avgRevenue": 289.78,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 49,
    "totalRevenue": 11200.36,
    "totalOrders": 10,
    "avgRevenue": 228.58,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 49,
    "totalRevenue": 15417.4,
    "totalOrders": 14,
    "avgRevenue": 314.64,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 49,
    "totalRevenue": 17462.18,
    "totalOrders": 14,
    "avgRevenue": 356.37,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 49,
    "totalRevenue": 15905.88,
    "totalOrders": 13,
    "avgRevenue": 324.61,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 49,
    "totalRevenue": 11685.95,
    "totalOrders": 11,
    "avgRevenue": 238.49,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 49,
    "totalRevenue": 20718.58,
    "totalOrders": 18,
    "avgRevenue": 422.83,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 49,
    "totalRevenue": 9999.43,
    "totalOrders": 11,
    "avgRevenue": 204.07,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 49,
    "totalRevenue": 10746.9,
    "totalOrders": 8,
    "avgRevenue": 219.32,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 42,
    "totalRevenue": 4899.29,
    "totalOrders": 4,
    "avgRevenue": 116.65,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 42,
    "totalRevenue": 3230.37,
    "totalOrders": 3,
    "avgRevenue": 76.91,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 42,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 42,
    "totalRevenue": 2792.87,
    "totalOrders": 2,
    "avgRevenue": 66.5,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 42,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 42,
    "totalRevenue": 743.3,
    "totalOrders": 1,
    "avgRevenue": 17.7,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 42,
    "totalRevenue": 4938.41,
    "totalOrders": 4,
    "avgRevenue": 117.58,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 42,
    "totalRevenue": 9796.13,
    "totalOrders": 8,
    "avgRevenue": 233.24,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 42,
    "totalRevenue": 14306.84,
    "totalOrders": 16,
    "avgRevenue": 340.64,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 42,
    "totalRevenue": 14180.19,
    "totalOrders": 15,
    "avgRevenue": 337.62,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 42,
    "totalRevenue": 16772.18,
    "totalOrders": 15,
    "avgRevenue": 399.34,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 42,
    "totalRevenue": 28607.28,
    "totalOrders": 18,
    "avgRevenue": 681.13,
    "avgOrders": 0.43
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 42,
    "totalRevenue": 20617.84,
    "totalOrders": 13,
    "avgRevenue": 490.9,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 42,
    "totalRevenue": 18835.39,
    "totalOrders": 17,
    "avgRevenue": 448.46,
    "avgOrders": 0.4
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 42,
    "totalRevenue": 12478.47,
    "totalOrders": 8,
    "avgRevenue": 297.11,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 42,
    "totalRevenue": 13239.26,
    "totalOrders": 10,
    "avgRevenue": 315.22,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 42,
    "totalRevenue": 14386.28,
    "totalOrders": 14,
    "avgRevenue": 342.53,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 42,
    "totalRevenue": 13205.43,
    "totalOrders": 11,
    "avgRevenue": 314.41,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 42,
    "totalRevenue": 19558.65,
    "totalOrders": 20,
    "avgRevenue": 465.68,
    "avgOrders": 0.48
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 42,
    "totalRevenue": 14297.14,
    "totalOrders": 13,
    "avgRevenue": 340.41,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 42,
    "totalRevenue": 10221.14,
    "totalOrders": 12,
    "avgRevenue": 243.36,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 42,
    "totalRevenue": 15796.55,
    "totalOrders": 13,
    "avgRevenue": 376.11,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 42,
    "totalRevenue": 11418.78,
    "totalOrders": 11,
    "avgRevenue": 271.88,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 42,
    "totalRevenue": 11867.96,
    "totalOrders": 9,
    "avgRevenue": 282.57,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 41,
    "totalRevenue": 2939.29,
    "totalOrders": 2,
    "avgRevenue": 71.69,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 41,
    "totalRevenue": 1500.03,
    "totalOrders": 2,
    "avgRevenue": 36.59,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 41,
    "totalRevenue": 754.47,
    "totalOrders": 1,
    "avgRevenue": 18.4,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 41,
    "totalRevenue": 2049.11,
    "totalOrders": 1,
    "avgRevenue": 49.98,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 41,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 41,
    "totalRevenue": 2513.41,
    "totalOrders": 3,
    "avgRevenue": 61.3,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 41,
    "totalRevenue": 6000.91,
    "totalOrders": 5,
    "avgRevenue": 146.36,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 41,
    "totalRevenue": 12466.15,
    "totalOrders": 6,
    "avgRevenue": 304.05,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 41,
    "totalRevenue": 9713.57,
    "totalOrders": 9,
    "avgRevenue": 236.92,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 41,
    "totalRevenue": 22226.72,
    "totalOrders": 15,
    "avgRevenue": 542.12,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 41,
    "totalRevenue": 12441.98,
    "totalOrders": 10,
    "avgRevenue": 303.46,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 41,
    "totalRevenue": 8007.63,
    "totalOrders": 10,
    "avgRevenue": 195.31,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 41,
    "totalRevenue": 20103.86,
    "totalOrders": 20,
    "avgRevenue": 490.34,
    "avgOrders": 0.49
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 41,
    "totalRevenue": 21321.22,
    "totalOrders": 15,
    "avgRevenue": 520.03,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 41,
    "totalRevenue": 10731.57,
    "totalOrders": 10,
    "avgRevenue": 261.75,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 41,
    "totalRevenue": 16241.8,
    "totalOrders": 11,
    "avgRevenue": 396.14,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 41,
    "totalRevenue": 6832.52,
    "totalOrders": 6,
    "avgRevenue": 166.65,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 41,
    "totalRevenue": 14562.76,
    "totalOrders": 14,
    "avgRevenue": 355.19,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 41,
    "totalRevenue": 13848.4,
    "totalOrders": 11,
    "avgRevenue": 337.77,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 41,
    "totalRevenue": 11955.86,
    "totalOrders": 8,
    "avgRevenue": 291.61,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 41,
    "totalRevenue": 27151.35,
    "totalOrders": 22,
    "avgRevenue": 662.23,
    "avgOrders": 0.54
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 41,
    "totalRevenue": 17818.55,
    "totalOrders": 14,
    "avgRevenue": 434.6,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 41,
    "totalRevenue": 10809.45,
    "totalOrders": 8,
    "avgRevenue": 263.65,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 41,
    "totalRevenue": 8305.71,
    "totalOrders": 5,
    "avgRevenue": 202.58,
    "avgOrders": 0.12
  }
];
