// Auto-generated by scripts/updateData.js — last update: 2026-05-19
// SK: hourly purchase behaviour (EUR), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataSK: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 72,
    "totalRevenue": 96.74,
    "totalOrders": 4,
    "avgRevenue": 1.34,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 72,
    "totalRevenue": 75.36,
    "totalOrders": 2,
    "avgRevenue": 1.05,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 72,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 72,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 72,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 72,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 72,
    "totalRevenue": 102.54,
    "totalOrders": 3,
    "avgRevenue": 1.42,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 72,
    "totalRevenue": 268.68,
    "totalOrders": 6,
    "avgRevenue": 3.73,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 72,
    "totalRevenue": 481.65,
    "totalOrders": 8,
    "avgRevenue": 6.69,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 72,
    "totalRevenue": 250.52,
    "totalOrders": 6,
    "avgRevenue": 3.48,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 72,
    "totalRevenue": 519.94,
    "totalOrders": 13,
    "avgRevenue": 7.22,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 72,
    "totalRevenue": 658.14,
    "totalOrders": 10,
    "avgRevenue": 9.14,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 72,
    "totalRevenue": 415.87,
    "totalOrders": 7,
    "avgRevenue": 5.78,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 72,
    "totalRevenue": 731.76,
    "totalOrders": 12,
    "avgRevenue": 10.16,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 72,
    "totalRevenue": 395.5,
    "totalOrders": 6,
    "avgRevenue": 5.49,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 72,
    "totalRevenue": 674.17,
    "totalOrders": 11,
    "avgRevenue": 9.36,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 72,
    "totalRevenue": 369.24,
    "totalOrders": 7,
    "avgRevenue": 5.13,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 72,
    "totalRevenue": 566.93,
    "totalOrders": 8,
    "avgRevenue": 7.87,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 72,
    "totalRevenue": 915.92,
    "totalOrders": 16,
    "avgRevenue": 12.72,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 72,
    "totalRevenue": 713.79,
    "totalOrders": 12,
    "avgRevenue": 9.91,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 72,
    "totalRevenue": 727.72,
    "totalOrders": 13,
    "avgRevenue": 10.11,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 72,
    "totalRevenue": 652.31,
    "totalOrders": 13,
    "avgRevenue": 9.06,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 72,
    "totalRevenue": 561.9,
    "totalOrders": 8,
    "avgRevenue": 7.8,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 72,
    "totalRevenue": 387.75,
    "totalOrders": 6,
    "avgRevenue": 5.39,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 67,
    "totalRevenue": 223.42,
    "totalOrders": 4,
    "avgRevenue": 3.33,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 67,
    "totalRevenue": 85.24,
    "totalOrders": 2,
    "avgRevenue": 1.27,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 67,
    "totalRevenue": 107.52,
    "totalOrders": 2,
    "avgRevenue": 1.6,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 67,
    "totalRevenue": 181.78,
    "totalOrders": 4,
    "avgRevenue": 2.71,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 67,
    "totalRevenue": 23.8,
    "totalOrders": 1,
    "avgRevenue": 0.36,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 67,
    "totalRevenue": 291.37,
    "totalOrders": 7,
    "avgRevenue": 4.35,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 67,
    "totalRevenue": 739.29,
    "totalOrders": 14,
    "avgRevenue": 11.03,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 67,
    "totalRevenue": 906.03,
    "totalOrders": 15,
    "avgRevenue": 13.52,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 67,
    "totalRevenue": 604.88,
    "totalOrders": 10,
    "avgRevenue": 9.03,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 67,
    "totalRevenue": 289.24,
    "totalOrders": 8,
    "avgRevenue": 4.32,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 67,
    "totalRevenue": 249.21,
    "totalOrders": 7,
    "avgRevenue": 3.72,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 67,
    "totalRevenue": 1103.68,
    "totalOrders": 17,
    "avgRevenue": 16.47,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 67,
    "totalRevenue": 532.03,
    "totalOrders": 9,
    "avgRevenue": 7.94,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 67,
    "totalRevenue": 636.96,
    "totalOrders": 13,
    "avgRevenue": 9.51,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 67,
    "totalRevenue": 860.21,
    "totalOrders": 21,
    "avgRevenue": 12.84,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 67,
    "totalRevenue": 519.94,
    "totalOrders": 9,
    "avgRevenue": 7.76,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 67,
    "totalRevenue": 814.56,
    "totalOrders": 11,
    "avgRevenue": 12.16,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 67,
    "totalRevenue": 1030.35,
    "totalOrders": 18,
    "avgRevenue": 15.38,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 67,
    "totalRevenue": 554.22,
    "totalOrders": 10,
    "avgRevenue": 8.27,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 67,
    "totalRevenue": 191.64,
    "totalOrders": 3,
    "avgRevenue": 2.86,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 71,
    "totalRevenue": 207.27,
    "totalOrders": 2,
    "avgRevenue": 2.92,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 71,
    "totalRevenue": 57.18,
    "totalOrders": 2,
    "avgRevenue": 0.81,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 71,
    "totalRevenue": 71.98,
    "totalOrders": 1,
    "avgRevenue": 1.01,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 71,
    "totalRevenue": 19.06,
    "totalOrders": 1,
    "avgRevenue": 0.27,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 71,
    "totalRevenue": 49.4,
    "totalOrders": 1,
    "avgRevenue": 0.7,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 71,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 71,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 71,
    "totalRevenue": 136.14,
    "totalOrders": 3,
    "avgRevenue": 1.92,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 71,
    "totalRevenue": 358.18,
    "totalOrders": 7,
    "avgRevenue": 5.04,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 71,
    "totalRevenue": 658.13,
    "totalOrders": 10,
    "avgRevenue": 9.27,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 71,
    "totalRevenue": 574.65,
    "totalOrders": 9,
    "avgRevenue": 8.09,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 71,
    "totalRevenue": 387.15,
    "totalOrders": 10,
    "avgRevenue": 5.45,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 71,
    "totalRevenue": 713.45,
    "totalOrders": 14,
    "avgRevenue": 10.05,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 71,
    "totalRevenue": 752.08,
    "totalOrders": 9,
    "avgRevenue": 10.59,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 71,
    "totalRevenue": 401.23,
    "totalOrders": 10,
    "avgRevenue": 5.65,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 71,
    "totalRevenue": 425.68,
    "totalOrders": 11,
    "avgRevenue": 6,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 71,
    "totalRevenue": 447.75,
    "totalOrders": 7,
    "avgRevenue": 6.31,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 71,
    "totalRevenue": 350.89,
    "totalOrders": 5,
    "avgRevenue": 4.94,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 71,
    "totalRevenue": 995.2,
    "totalOrders": 17,
    "avgRevenue": 14.02,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 71,
    "totalRevenue": 942.7,
    "totalOrders": 17,
    "avgRevenue": 13.28,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 71,
    "totalRevenue": 530.31,
    "totalOrders": 9,
    "avgRevenue": 7.47,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 71,
    "totalRevenue": 816.03,
    "totalOrders": 15,
    "avgRevenue": 11.49,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 71,
    "totalRevenue": 768.21,
    "totalOrders": 11,
    "avgRevenue": 10.82,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 71,
    "totalRevenue": 35.02,
    "totalOrders": 2,
    "avgRevenue": 0.49,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 63,
    "totalRevenue": 138.43,
    "totalOrders": 3,
    "avgRevenue": 2.2,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 63,
    "totalRevenue": 34.76,
    "totalOrders": 1,
    "avgRevenue": 0.55,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 63,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 63,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 63,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 63,
    "totalRevenue": 122.19,
    "totalOrders": 3,
    "avgRevenue": 1.94,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 63,
    "totalRevenue": 78.45,
    "totalOrders": 2,
    "avgRevenue": 1.25,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 63,
    "totalRevenue": 172.02,
    "totalOrders": 5,
    "avgRevenue": 2.73,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 63,
    "totalRevenue": 201.94,
    "totalOrders": 5,
    "avgRevenue": 3.21,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 63,
    "totalRevenue": 276.7,
    "totalOrders": 8,
    "avgRevenue": 4.39,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 63,
    "totalRevenue": 351.98,
    "totalOrders": 9,
    "avgRevenue": 5.59,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 63,
    "totalRevenue": 429.27,
    "totalOrders": 11,
    "avgRevenue": 6.81,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 63,
    "totalRevenue": 319.73,
    "totalOrders": 7,
    "avgRevenue": 5.08,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 63,
    "totalRevenue": 351.75,
    "totalOrders": 9,
    "avgRevenue": 5.58,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 63,
    "totalRevenue": 74.22,
    "totalOrders": 2,
    "avgRevenue": 1.18,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 63,
    "totalRevenue": 273.21,
    "totalOrders": 3,
    "avgRevenue": 4.34,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 63,
    "totalRevenue": 499.55,
    "totalOrders": 8,
    "avgRevenue": 7.93,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 63,
    "totalRevenue": 773.72,
    "totalOrders": 9,
    "avgRevenue": 12.28,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 63,
    "totalRevenue": 410.38,
    "totalOrders": 7,
    "avgRevenue": 6.51,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 63,
    "totalRevenue": 552.91,
    "totalOrders": 14,
    "avgRevenue": 8.78,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 63,
    "totalRevenue": 455.58,
    "totalOrders": 8,
    "avgRevenue": 7.23,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 63,
    "totalRevenue": 428.78,
    "totalOrders": 9,
    "avgRevenue": 6.81,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 63,
    "totalRevenue": 294.89,
    "totalOrders": 6,
    "avgRevenue": 4.68,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 63,
    "totalRevenue": 392.7,
    "totalOrders": 5,
    "avgRevenue": 6.23,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 67,
    "totalRevenue": 22.82,
    "totalOrders": 1,
    "avgRevenue": 0.34,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 67,
    "totalRevenue": 50.26,
    "totalOrders": 2,
    "avgRevenue": 0.75,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 67,
    "totalRevenue": 77.82,
    "totalOrders": 2,
    "avgRevenue": 1.16,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 67,
    "totalRevenue": 25.44,
    "totalOrders": 1,
    "avgRevenue": 0.38,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 67,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 67,
    "totalRevenue": 26.41,
    "totalOrders": 1,
    "avgRevenue": 0.39,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 67,
    "totalRevenue": 193.14,
    "totalOrders": 3,
    "avgRevenue": 2.88,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 67,
    "totalRevenue": 134.41,
    "totalOrders": 2,
    "avgRevenue": 2.01,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 67,
    "totalRevenue": 87.13,
    "totalOrders": 1,
    "avgRevenue": 1.3,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 67,
    "totalRevenue": 414.97,
    "totalOrders": 9,
    "avgRevenue": 6.19,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 67,
    "totalRevenue": 684.33,
    "totalOrders": 12,
    "avgRevenue": 10.21,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 67,
    "totalRevenue": 789.41,
    "totalOrders": 10,
    "avgRevenue": 11.78,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 67,
    "totalRevenue": 648.16,
    "totalOrders": 5,
    "avgRevenue": 9.67,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 67,
    "totalRevenue": 334.8,
    "totalOrders": 7,
    "avgRevenue": 5,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 67,
    "totalRevenue": 518.71,
    "totalOrders": 7,
    "avgRevenue": 7.74,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 67,
    "totalRevenue": 326.99,
    "totalOrders": 6,
    "avgRevenue": 4.88,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 67,
    "totalRevenue": 314.07,
    "totalOrders": 4,
    "avgRevenue": 4.69,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 67,
    "totalRevenue": 176.27,
    "totalOrders": 4,
    "avgRevenue": 2.63,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 67,
    "totalRevenue": 673.36,
    "totalOrders": 12,
    "avgRevenue": 10.05,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 67,
    "totalRevenue": 233.44,
    "totalOrders": 5,
    "avgRevenue": 3.48,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 67,
    "totalRevenue": 635.99,
    "totalOrders": 11,
    "avgRevenue": 9.49,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 67,
    "totalRevenue": 657.19,
    "totalOrders": 13,
    "avgRevenue": 9.81,
    "avgOrders": 0.19
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 67,
    "totalRevenue": 239.47,
    "totalOrders": 3,
    "avgRevenue": 3.57,
    "avgOrders": 0.04
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 67,
    "totalRevenue": 72.92,
    "totalOrders": 1,
    "avgRevenue": 1.09,
    "avgOrders": 0.01
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 62,
    "totalRevenue": 88.07,
    "totalOrders": 1,
    "avgRevenue": 1.42,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 62,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 62,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 62,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 62,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 62,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 62,
    "totalRevenue": 68.93,
    "totalOrders": 1,
    "avgRevenue": 1.11,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 62,
    "totalRevenue": 310.11,
    "totalOrders": 5,
    "avgRevenue": 5,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 62,
    "totalRevenue": 220.36,
    "totalOrders": 5,
    "avgRevenue": 3.55,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 62,
    "totalRevenue": 896.26,
    "totalOrders": 13,
    "avgRevenue": 14.46,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 62,
    "totalRevenue": 305.34,
    "totalOrders": 6,
    "avgRevenue": 4.92,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 62,
    "totalRevenue": 235.3,
    "totalOrders": 6,
    "avgRevenue": 3.8,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 62,
    "totalRevenue": 194.91,
    "totalOrders": 7,
    "avgRevenue": 3.14,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 62,
    "totalRevenue": 553.62,
    "totalOrders": 10,
    "avgRevenue": 8.93,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 62,
    "totalRevenue": 304.46,
    "totalOrders": 5,
    "avgRevenue": 4.91,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 62,
    "totalRevenue": 341.46,
    "totalOrders": 7,
    "avgRevenue": 5.51,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 62,
    "totalRevenue": 695.26,
    "totalOrders": 7,
    "avgRevenue": 11.21,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 62,
    "totalRevenue": 412.19,
    "totalOrders": 7,
    "avgRevenue": 6.65,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 62,
    "totalRevenue": 501.56,
    "totalOrders": 8,
    "avgRevenue": 8.09,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 62,
    "totalRevenue": 261.66,
    "totalOrders": 5,
    "avgRevenue": 4.22,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 62,
    "totalRevenue": 178.09,
    "totalOrders": 5,
    "avgRevenue": 2.87,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 62,
    "totalRevenue": 288.61,
    "totalOrders": 8,
    "avgRevenue": 4.65,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 62,
    "totalRevenue": 182.09,
    "totalOrders": 3,
    "avgRevenue": 2.94,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 62,
    "totalRevenue": 463.17,
    "totalOrders": 7,
    "avgRevenue": 7.47,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 59,
    "totalRevenue": 145.7,
    "totalOrders": 3,
    "avgRevenue": 2.47,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 59,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 59,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 59,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 59,
    "totalRevenue": 119.61,
    "totalOrders": 1,
    "avgRevenue": 2.03,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 59,
    "totalRevenue": 68.78,
    "totalOrders": 1,
    "avgRevenue": 1.17,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 59,
    "totalRevenue": 58.88,
    "totalOrders": 2,
    "avgRevenue": 1,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 59,
    "totalRevenue": 511.21,
    "totalOrders": 7,
    "avgRevenue": 8.66,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 59,
    "totalRevenue": 338.65,
    "totalOrders": 7,
    "avgRevenue": 5.74,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 59,
    "totalRevenue": 473.4,
    "totalOrders": 8,
    "avgRevenue": 8.02,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 59,
    "totalRevenue": 445.63,
    "totalOrders": 7,
    "avgRevenue": 7.55,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 59,
    "totalRevenue": 471.46,
    "totalOrders": 8,
    "avgRevenue": 7.99,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 59,
    "totalRevenue": 432.77,
    "totalOrders": 7,
    "avgRevenue": 7.34,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 59,
    "totalRevenue": 129.91,
    "totalOrders": 3,
    "avgRevenue": 2.2,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 59,
    "totalRevenue": 185.53,
    "totalOrders": 5,
    "avgRevenue": 3.14,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 59,
    "totalRevenue": 296.11,
    "totalOrders": 6,
    "avgRevenue": 5.02,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 59,
    "totalRevenue": 394.42,
    "totalOrders": 9,
    "avgRevenue": 6.69,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 59,
    "totalRevenue": 469.8,
    "totalOrders": 7,
    "avgRevenue": 7.96,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 59,
    "totalRevenue": 247.55,
    "totalOrders": 8,
    "avgRevenue": 4.2,
    "avgOrders": 0.14
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 59,
    "totalRevenue": 433.59,
    "totalOrders": 6,
    "avgRevenue": 7.35,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 59,
    "totalRevenue": 630.49,
    "totalOrders": 10,
    "avgRevenue": 10.69,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 59,
    "totalRevenue": 248.32,
    "totalOrders": 6,
    "avgRevenue": 4.21,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 59,
    "totalRevenue": 556.56,
    "totalOrders": 9,
    "avgRevenue": 9.43,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 59,
    "totalRevenue": 108.42,
    "totalOrders": 3,
    "avgRevenue": 1.84,
    "avgOrders": 0.05
  }
];
