// Auto-generated by scripts/updateData.js — last update: 2026-05-20
// CZ: daily margin data (CZK). purchaseCost = nákupní cena, revenue = tržby bez DPH.

export interface MarginDailyRecord {
  date: string;        // ISO "2025-05-25"
  purchaseCost: number; // nákupní cena (součet za den)
  revenue: number;      // tržby bez DPH (součet za den)
}

export const marginDataCZ: MarginDailyRecord[] = [
  {
    "date": "2025-05-25",
    "purchaseCost": 786.59,
    "revenue": 1338.02
  },
  {
    "date": "2025-05-28",
    "purchaseCost": 1034.18,
    "revenue": 1699.18
  },
  {
    "date": "2025-05-29",
    "purchaseCost": 1797.48,
    "revenue": 2548.76
  },
  {
    "date": "2025-05-30",
    "purchaseCost": 1541.15,
    "revenue": 2754.57
  },
  {
    "date": "2025-05-31",
    "purchaseCost": 1149.34,
    "revenue": 1693.39
  },
  {
    "date": "2025-06-01",
    "purchaseCost": 726.83,
    "revenue": 1241.32
  },
  {
    "date": "2025-06-02",
    "purchaseCost": 1860.35,
    "revenue": 3138.02
  },
  {
    "date": "2025-06-03",
    "purchaseCost": 2305.68,
    "revenue": 3827.71
  },
  {
    "date": "2025-06-04",
    "purchaseCost": 1114.1,
    "revenue": 1795.87
  },
  {
    "date": "2025-06-05",
    "purchaseCost": 886.84,
    "revenue": 1601.66
  },
  {
    "date": "2025-06-06",
    "purchaseCost": 265.78,
    "revenue": 498.35
  },
  {
    "date": "2025-06-07",
    "purchaseCost": 4046.83,
    "revenue": 6550.43
  },
  {
    "date": "2025-06-08",
    "purchaseCost": 1267.4,
    "revenue": 2217.36
  },
  {
    "date": "2025-06-09",
    "purchaseCost": 2757.23,
    "revenue": 4613.23
  },
  {
    "date": "2025-06-10",
    "purchaseCost": 2535.5,
    "revenue": 4050.41
  },
  {
    "date": "2025-06-12",
    "purchaseCost": 1082.65,
    "revenue": 1745.46
  },
  {
    "date": "2025-06-13",
    "purchaseCost": 1645.31,
    "revenue": 2926.46
  },
  {
    "date": "2025-06-15",
    "purchaseCost": 735.33,
    "revenue": 1320.66
  },
  {
    "date": "2025-06-16",
    "purchaseCost": 2470.62,
    "revenue": 4238.44
  },
  {
    "date": "2025-06-17",
    "purchaseCost": 2387.18,
    "revenue": 3814.88
  },
  {
    "date": "2025-06-18",
    "purchaseCost": 196.24,
    "revenue": 354.39
  },
  {
    "date": "2025-06-19",
    "purchaseCost": 1965.98,
    "revenue": 3128.94
  },
  {
    "date": "2025-06-20",
    "purchaseCost": 535.24,
    "revenue": 932.24
  },
  {
    "date": "2025-06-22",
    "purchaseCost": 729.12,
    "revenue": 1127.19
  },
  {
    "date": "2025-06-23",
    "purchaseCost": 4247.58,
    "revenue": 6869.09
  },
  {
    "date": "2025-06-24",
    "purchaseCost": 4365.51,
    "revenue": 7140.49
  },
  {
    "date": "2025-06-26",
    "purchaseCost": 312.48,
    "revenue": 606.62
  },
  {
    "date": "2025-06-28",
    "purchaseCost": 763.89,
    "revenue": 1177.02
  },
  {
    "date": "2025-06-30",
    "purchaseCost": 1776.17,
    "revenue": 2857.04
  },
  {
    "date": "2025-07-01",
    "purchaseCost": 1161.75,
    "revenue": 1664.47
  },
  {
    "date": "2025-07-02",
    "purchaseCost": 520.8,
    "revenue": 825.21
  },
  {
    "date": "2025-07-03",
    "purchaseCost": 2159.46,
    "revenue": 3323.96
  },
  {
    "date": "2025-07-04",
    "purchaseCost": 694.19,
    "revenue": 1224.38
  },
  {
    "date": "2025-07-05",
    "purchaseCost": 1691.31,
    "revenue": 2910.91
  },
  {
    "date": "2025-07-06",
    "purchaseCost": 461.94,
    "revenue": 814.05
  },
  {
    "date": "2025-07-07",
    "purchaseCost": 714.75,
    "revenue": 1221.49
  },
  {
    "date": "2025-07-08",
    "purchaseCost": 2028.5,
    "revenue": 3608.28
  },
  {
    "date": "2025-07-09",
    "purchaseCost": 365.7,
    "revenue": 725.63
  },
  {
    "date": "2025-07-10",
    "purchaseCost": 887.8,
    "revenue": 1361.99
  },
  {
    "date": "2025-07-11",
    "purchaseCost": 887.8,
    "revenue": 1328.93
  },
  {
    "date": "2025-07-12",
    "purchaseCost": 104.16,
    "revenue": 238.02
  },
  {
    "date": "2025-07-13",
    "purchaseCost": 729.11,
    "revenue": 1181
  },
  {
    "date": "2025-07-14",
    "purchaseCost": 1086.67,
    "revenue": 1669.42
  },
  {
    "date": "2025-07-15",
    "purchaseCost": 1650.89,
    "revenue": 2638.85
  },
  {
    "date": "2025-07-16",
    "purchaseCost": 945.85,
    "revenue": 1664.47
  },
  {
    "date": "2025-07-17",
    "purchaseCost": 3317.69,
    "revenue": 5467.79
  },
  {
    "date": "2025-07-20",
    "purchaseCost": 10806.63,
    "revenue": 16454.2
  },
  {
    "date": "2025-07-21",
    "purchaseCost": 2007.1,
    "revenue": 3102.49
  },
  {
    "date": "2025-07-22",
    "purchaseCost": 878.42,
    "revenue": 1622.33
  },
  {
    "date": "2025-07-23",
    "purchaseCost": 909.68,
    "revenue": 1360.33
  },
  {
    "date": "2025-07-24",
    "purchaseCost": 689.29,
    "revenue": 1214.06
  },
  {
    "date": "2025-07-25",
    "purchaseCost": 295.41,
    "revenue": 579.35
  },
  {
    "date": "2025-07-26",
    "purchaseCost": 473.13,
    "revenue": 865.29
  },
  {
    "date": "2025-07-27",
    "purchaseCost": 2278.46,
    "revenue": 4018.22
  },
  {
    "date": "2025-07-28",
    "purchaseCost": 1330.54,
    "revenue": 2167.43
  },
  {
    "date": "2025-07-29",
    "purchaseCost": 2561.28,
    "revenue": 4435.56
  },
  {
    "date": "2025-07-30",
    "purchaseCost": 468.48,
    "revenue": 825.62
  },
  {
    "date": "2025-07-31",
    "purchaseCost": 1708.69,
    "revenue": 2855.39
  },
  {
    "date": "2025-08-02",
    "purchaseCost": 3691.21,
    "revenue": 5599.18
  },
  {
    "date": "2025-08-03",
    "purchaseCost": 1597.01,
    "revenue": 2674.38
  },
  {
    "date": "2025-08-04",
    "purchaseCost": 2241.3,
    "revenue": 3326.47
  },
  {
    "date": "2025-08-05",
    "purchaseCost": 2158.29,
    "revenue": 3368.2
  },
  {
    "date": "2025-08-07",
    "purchaseCost": 683.9,
    "revenue": 1239.68
  },
  {
    "date": "2025-08-08",
    "purchaseCost": 1450.08,
    "revenue": 2265.3
  },
  {
    "date": "2025-08-09",
    "purchaseCost": 2302.85,
    "revenue": 3530.59
  },
  {
    "date": "2025-08-10",
    "purchaseCost": 2604.67,
    "revenue": 4026.04
  },
  {
    "date": "2025-08-11",
    "purchaseCost": 207.02,
    "revenue": 437.19
  },
  {
    "date": "2025-08-12",
    "purchaseCost": 1512.76,
    "revenue": 2338.19
  },
  {
    "date": "2025-08-13",
    "purchaseCost": 1079.8,
    "revenue": 1772.74
  },
  {
    "date": "2025-08-14",
    "purchaseCost": 1969.08,
    "revenue": 3214.06
  },
  {
    "date": "2025-08-17",
    "purchaseCost": 2455.1,
    "revenue": 4153.74
  },
  {
    "date": "2025-08-18",
    "purchaseCost": 1208.1,
    "revenue": 1790.41
  },
  {
    "date": "2025-08-19",
    "purchaseCost": 167.18,
    "revenue": 372.73
  },
  {
    "date": "2025-08-20",
    "purchaseCost": 3060.39,
    "revenue": 4749.44
  },
  {
    "date": "2025-08-21",
    "purchaseCost": 297.46,
    "revenue": 615.71
  },
  {
    "date": "2025-08-22",
    "purchaseCost": 1492.51,
    "revenue": 2326.45
  },
  {
    "date": "2025-08-25",
    "purchaseCost": 3009.31,
    "revenue": 4774.81
  },
  {
    "date": "2025-08-27",
    "purchaseCost": 577.27,
    "revenue": 922.32
  },
  {
    "date": "2025-08-28",
    "purchaseCost": 628.54,
    "revenue": 1114.88
  },
  {
    "date": "2025-08-29",
    "purchaseCost": 2488.1,
    "revenue": 4041.35
  },
  {
    "date": "2025-08-31",
    "purchaseCost": 527.65,
    "revenue": 952.9
  },
  {
    "date": "2025-09-01",
    "purchaseCost": 2059.18,
    "revenue": 3419.84
  },
  {
    "date": "2025-09-02",
    "purchaseCost": 8827.36,
    "revenue": 13984.73
  },
  {
    "date": "2025-09-03",
    "purchaseCost": 1063.8,
    "revenue": 1710.75
  },
  {
    "date": "2025-09-04",
    "purchaseCost": 506.1,
    "revenue": 804.13
  },
  {
    "date": "2025-09-05",
    "purchaseCost": 1250.89,
    "revenue": 2097.53
  },
  {
    "date": "2025-09-08",
    "purchaseCost": 323.58,
    "revenue": 591.74
  },
  {
    "date": "2025-09-10",
    "purchaseCost": 1626.56,
    "revenue": 2882.66
  },
  {
    "date": "2025-09-11",
    "purchaseCost": 797.36,
    "revenue": 1458.68
  },
  {
    "date": "2025-09-12",
    "purchaseCost": 2574.6,
    "revenue": 3997.11
  },
  {
    "date": "2025-09-14",
    "purchaseCost": 887.8,
    "revenue": 1604.14
  },
  {
    "date": "2025-09-16",
    "purchaseCost": 912.29,
    "revenue": 1561.98
  },
  {
    "date": "2025-09-17",
    "purchaseCost": 1870.95,
    "revenue": 3152.9
  },
  {
    "date": "2025-09-19",
    "purchaseCost": 359.5,
    "revenue": 648.76
  },
  {
    "date": "2025-09-20",
    "purchaseCost": 2019.36,
    "revenue": 3390.11
  },
  {
    "date": "2025-09-22",
    "purchaseCost": 493.04,
    "revenue": 864.47
  },
  {
    "date": "2025-09-23",
    "purchaseCost": 3886.37,
    "revenue": 6753.42
  },
  {
    "date": "2025-09-24",
    "purchaseCost": 1357.35,
    "revenue": 2342.58
  },
  {
    "date": "2025-09-25",
    "purchaseCost": 4371.74,
    "revenue": 7147.96
  },
  {
    "date": "2025-09-27",
    "purchaseCost": 3637.25,
    "revenue": 5822.09
  },
  {
    "date": "2025-09-28",
    "purchaseCost": 2644.48,
    "revenue": 4212.41
  },
  {
    "date": "2025-09-29",
    "purchaseCost": 2128.98,
    "revenue": 3602.5
  },
  {
    "date": "2025-09-30",
    "purchaseCost": 1102.01,
    "revenue": 1873.97
  },
  {
    "date": "2025-10-01",
    "purchaseCost": 488.15,
    "revenue": 776.86
  },
  {
    "date": "2025-10-02",
    "purchaseCost": 1806.3,
    "revenue": 2746.3
  },
  {
    "date": "2025-10-03",
    "purchaseCost": 1638.64,
    "revenue": 2814.89
  },
  {
    "date": "2025-10-05",
    "purchaseCost": 599.42,
    "revenue": 1036.37
  },
  {
    "date": "2025-10-06",
    "purchaseCost": 1068.45,
    "revenue": 1722.32
  },
  {
    "date": "2025-10-08",
    "purchaseCost": 1139.9,
    "revenue": 2044.64
  },
  {
    "date": "2025-10-09",
    "purchaseCost": 1295.6,
    "revenue": 1880.33
  },
  {
    "date": "2025-10-10",
    "purchaseCost": 1064.79,
    "revenue": 1857.03
  },
  {
    "date": "2025-10-11",
    "purchaseCost": 3735.53,
    "revenue": 5476.87
  },
  {
    "date": "2025-10-12",
    "purchaseCost": 2826.34,
    "revenue": 4552.07
  },
  {
    "date": "2025-10-13",
    "purchaseCost": 4193.58,
    "revenue": 6541.42
  },
  {
    "date": "2025-10-14",
    "purchaseCost": 470.2,
    "revenue": 783.89
  },
  {
    "date": "2025-10-15",
    "purchaseCost": 2360.83,
    "revenue": 3935.97
  },
  {
    "date": "2025-10-16",
    "purchaseCost": 1371.97,
    "revenue": 2345.05
  },
  {
    "date": "2025-10-17",
    "purchaseCost": 2233.32,
    "revenue": 3834.73
  },
  {
    "date": "2025-10-18",
    "purchaseCost": 4018.83,
    "revenue": 6468.63
  },
  {
    "date": "2025-10-19",
    "purchaseCost": 2654.77,
    "revenue": 4449.6
  },
  {
    "date": "2025-10-21",
    "purchaseCost": 3659.83,
    "revenue": 5948.78
  },
  {
    "date": "2025-10-22",
    "purchaseCost": 2774.1,
    "revenue": 4330.18
  },
  {
    "date": "2025-10-23",
    "purchaseCost": 1340.07,
    "revenue": 2263.63
  },
  {
    "date": "2025-10-24",
    "purchaseCost": 2148.82,
    "revenue": 3462.4
  },
  {
    "date": "2025-10-25",
    "purchaseCost": 726.83,
    "revenue": 1176.86
  },
  {
    "date": "2025-10-26",
    "purchaseCost": 2466.87,
    "revenue": 4124.8
  },
  {
    "date": "2025-10-27",
    "purchaseCost": 3235.75,
    "revenue": 5511.59
  },
  {
    "date": "2025-10-28",
    "purchaseCost": 5744.55,
    "revenue": 9054.98
  },
  {
    "date": "2025-10-29",
    "purchaseCost": 3734,
    "revenue": 6231
  },
  {
    "date": "2025-10-30",
    "purchaseCost": 2532.31,
    "revenue": 4288.44
  },
  {
    "date": "2025-10-31",
    "purchaseCost": 556.71,
    "revenue": 966.95
  },
  {
    "date": "2025-11-02",
    "purchaseCost": 3204.09,
    "revenue": 4907.85
  },
  {
    "date": "2025-11-03",
    "purchaseCost": 2647.33,
    "revenue": 4228.11
  },
  {
    "date": "2025-11-04",
    "purchaseCost": 1153.27,
    "revenue": 2000.01
  },
  {
    "date": "2025-11-05",
    "purchaseCost": 3012.47,
    "revenue": 4956.21
  },
  {
    "date": "2025-11-06",
    "purchaseCost": 6916.19,
    "revenue": 10659.93
  },
  {
    "date": "2025-11-07",
    "purchaseCost": 3314.84,
    "revenue": 5133.89
  },
  {
    "date": "2025-11-08",
    "purchaseCost": 3520.55,
    "revenue": 5556.2
  },
  {
    "date": "2025-11-09",
    "purchaseCost": 1908.86,
    "revenue": 3307.85
  },
  {
    "date": "2025-11-10",
    "purchaseCost": 3390.53,
    "revenue": 5690.51
  },
  {
    "date": "2025-11-11",
    "purchaseCost": 5087.76,
    "revenue": 8487.63
  },
  {
    "date": "2025-11-12",
    "purchaseCost": 2678.88,
    "revenue": 4584.73
  },
  {
    "date": "2025-11-13",
    "purchaseCost": 10942.58,
    "revenue": 17626.08
  },
  {
    "date": "2025-11-14",
    "purchaseCost": 4683.75,
    "revenue": 7989.61
  },
  {
    "date": "2025-11-15",
    "purchaseCost": 1562.43,
    "revenue": 2607.45
  },
  {
    "date": "2025-11-16",
    "purchaseCost": 6644.8,
    "revenue": 10633.51
  },
  {
    "date": "2025-11-17",
    "purchaseCost": 1032.37,
    "revenue": 1868.61
  },
  {
    "date": "2025-11-18",
    "purchaseCost": 8323.18,
    "revenue": 13428.39
  },
  {
    "date": "2025-11-19",
    "purchaseCost": 6691.03,
    "revenue": 10053.97
  },
  {
    "date": "2025-11-20",
    "purchaseCost": 6447.05,
    "revenue": 10700.19
  },
  {
    "date": "2025-11-21",
    "purchaseCost": 10915.26,
    "revenue": 18774.27
  },
  {
    "date": "2025-11-22",
    "purchaseCost": 4216.41,
    "revenue": 7570.57
  },
  {
    "date": "2025-11-23",
    "purchaseCost": 5523.44,
    "revenue": 9642.04
  },
  {
    "date": "2025-11-24",
    "purchaseCost": 1936.1,
    "revenue": 3757.13
  },
  {
    "date": "2025-11-25",
    "purchaseCost": 5717.27,
    "revenue": 9391.1
  },
  {
    "date": "2025-11-26",
    "purchaseCost": 6573.82,
    "revenue": 11608.06
  },
  {
    "date": "2025-11-27",
    "purchaseCost": 3093.1,
    "revenue": 5708.06
  },
  {
    "date": "2025-11-28",
    "purchaseCost": 4543.25,
    "revenue": 7750
  },
  {
    "date": "2025-11-29",
    "purchaseCost": 2881.47,
    "revenue": 5232.13
  },
  {
    "date": "2025-11-30",
    "purchaseCost": 4617.04,
    "revenue": 8493.76
  },
  {
    "date": "2025-12-01",
    "purchaseCost": 11477.87,
    "revenue": 19969.66
  },
  {
    "date": "2025-12-02",
    "purchaseCost": 9428.93,
    "revenue": 16009.76
  },
  {
    "date": "2025-12-03",
    "purchaseCost": 10292.58,
    "revenue": 18396.32
  },
  {
    "date": "2025-12-04",
    "purchaseCost": 5901.02,
    "revenue": 10575.02
  },
  {
    "date": "2025-12-05",
    "purchaseCost": 3383.87,
    "revenue": 6343.75
  },
  {
    "date": "2025-12-06",
    "purchaseCost": 4235.54,
    "revenue": 7382.68
  },
  {
    "date": "2025-12-07",
    "purchaseCost": 6165.07,
    "revenue": 11258.9
  },
  {
    "date": "2025-12-08",
    "purchaseCost": 10869.26,
    "revenue": 18060.71
  },
  {
    "date": "2025-12-09",
    "purchaseCost": 6128.39,
    "revenue": 11193.28
  },
  {
    "date": "2025-12-10",
    "purchaseCost": 8205.46,
    "revenue": 14164.77
  },
  {
    "date": "2025-12-11",
    "purchaseCost": 10661.69,
    "revenue": 18317.43
  },
  {
    "date": "2025-12-12",
    "purchaseCost": 6257.97,
    "revenue": 11327.71
  },
  {
    "date": "2025-12-13",
    "purchaseCost": 5410.1,
    "revenue": 10009.85
  },
  {
    "date": "2025-12-14",
    "purchaseCost": 9884.95,
    "revenue": 17977.25
  },
  {
    "date": "2025-12-15",
    "purchaseCost": 16374.88,
    "revenue": 28052.74
  },
  {
    "date": "2025-12-16",
    "purchaseCost": 7804.09,
    "revenue": 14564.35
  },
  {
    "date": "2025-12-17",
    "purchaseCost": 3960.44,
    "revenue": 6747.33
  },
  {
    "date": "2025-12-18",
    "purchaseCost": 1006.66,
    "revenue": 1974.11
  },
  {
    "date": "2025-12-20",
    "purchaseCost": 888.55,
    "revenue": 1548.22
  },
  {
    "date": "2025-12-25",
    "purchaseCost": 522.33,
    "revenue": 1021.44
  },
  {
    "date": "2025-12-27",
    "purchaseCost": 1159.18,
    "revenue": 1869.64
  },
  {
    "date": "2025-12-28",
    "purchaseCost": 1316.97,
    "revenue": 2406.25
  },
  {
    "date": "2025-12-29",
    "purchaseCost": 1126.11,
    "revenue": 1961.61
  },
  {
    "date": "2025-12-30",
    "purchaseCost": 1536.54,
    "revenue": 2868.73
  },
  {
    "date": "2025-12-31",
    "purchaseCost": 272.61,
    "revenue": 550.89
  },
  {
    "date": "2026-01-02",
    "purchaseCost": 3739.88,
    "revenue": 6699.1
  },
  {
    "date": "2026-01-03",
    "purchaseCost": 1466.42,
    "revenue": 2666.07
  },
  {
    "date": "2026-01-04",
    "purchaseCost": 4755.31,
    "revenue": 8165.64
  },
  {
    "date": "2026-01-05",
    "purchaseCost": 1899.46,
    "revenue": 3386.61
  },
  {
    "date": "2026-01-06",
    "purchaseCost": 2302.37,
    "revenue": 4383.92
  },
  {
    "date": "2026-01-07",
    "purchaseCost": 502.31,
    "revenue": 1061.59
  },
  {
    "date": "2026-01-08",
    "purchaseCost": 1483.66,
    "revenue": 2692.85
  },
  {
    "date": "2026-01-10",
    "purchaseCost": 288.48,
    "revenue": 578.58
  },
  {
    "date": "2026-01-11",
    "purchaseCost": 3977.58,
    "revenue": 7233.52
  },
  {
    "date": "2026-01-12",
    "purchaseCost": 3356.94,
    "revenue": 5718.83
  },
  {
    "date": "2026-01-13",
    "purchaseCost": 3979.02,
    "revenue": 7224.03
  },
  {
    "date": "2026-01-14",
    "purchaseCost": 309.48,
    "revenue": 615.18
  },
  {
    "date": "2026-01-15",
    "purchaseCost": 1637.1,
    "revenue": 2998.22
  },
  {
    "date": "2026-01-17",
    "purchaseCost": 433.1,
    "revenue": 830.36
  },
  {
    "date": "2026-01-18",
    "purchaseCost": 1096.04,
    "revenue": 2060.72
  },
  {
    "date": "2026-01-19",
    "purchaseCost": 2913.48,
    "revenue": 5176.34
  },
  {
    "date": "2026-01-20",
    "purchaseCost": 1993.55,
    "revenue": 3469.67
  },
  {
    "date": "2026-01-21",
    "purchaseCost": 2601.93,
    "revenue": 4479.47
  },
  {
    "date": "2026-01-22",
    "purchaseCost": 2987.31,
    "revenue": 5908.93
  },
  {
    "date": "2026-01-23",
    "purchaseCost": 801.2,
    "revenue": 1492.85
  },
  {
    "date": "2026-01-24",
    "purchaseCost": 10337.39,
    "revenue": 17951.75
  },
  {
    "date": "2026-01-25",
    "purchaseCost": 5475.28,
    "revenue": 10049.61
  },
  {
    "date": "2026-01-26",
    "purchaseCost": 3675.24,
    "revenue": 6889.29
  },
  {
    "date": "2026-01-27",
    "purchaseCost": 6615.15,
    "revenue": 11977.7
  },
  {
    "date": "2026-01-28",
    "purchaseCost": 4535.74,
    "revenue": 8641.99
  },
  {
    "date": "2026-01-29",
    "purchaseCost": 3298.55,
    "revenue": 6263.37
  },
  {
    "date": "2026-01-30",
    "purchaseCost": 4289.99,
    "revenue": 7709.83
  },
  {
    "date": "2026-01-31",
    "purchaseCost": 3120.97,
    "revenue": 5708.94
  },
  {
    "date": "2026-02-01",
    "purchaseCost": 5255.96,
    "revenue": 9655.4
  },
  {
    "date": "2026-02-02",
    "purchaseCost": 4311.53,
    "revenue": 7555.8
  },
  {
    "date": "2026-02-03",
    "purchaseCost": 7659.55,
    "revenue": 13211.2
  },
  {
    "date": "2026-02-04",
    "purchaseCost": 2603.1,
    "revenue": 4638.39
  },
  {
    "date": "2026-02-05",
    "purchaseCost": 1754.59,
    "revenue": 3294.65
  },
  {
    "date": "2026-02-06",
    "purchaseCost": 3328.52,
    "revenue": 5699.12
  },
  {
    "date": "2026-02-07",
    "purchaseCost": 5889.55,
    "revenue": 9745.11
  },
  {
    "date": "2026-02-08",
    "purchaseCost": 5593.04,
    "revenue": 10330.41
  },
  {
    "date": "2026-02-09",
    "purchaseCost": 4825.51,
    "revenue": 8641.99
  },
  {
    "date": "2026-02-10",
    "purchaseCost": 6004.25,
    "revenue": 9878.11
  },
  {
    "date": "2026-02-11",
    "purchaseCost": 4150.46,
    "revenue": 7592.88
  },
  {
    "date": "2026-02-12",
    "purchaseCost": 4391.49,
    "revenue": 7833.06
  },
  {
    "date": "2026-02-13",
    "purchaseCost": 4041.44,
    "revenue": 7437.97
  },
  {
    "date": "2026-02-14",
    "purchaseCost": 7980.32,
    "revenue": 14012.87
  },
  {
    "date": "2026-02-15",
    "purchaseCost": 5523.2,
    "revenue": 9359.46
  },
  {
    "date": "2026-02-16",
    "purchaseCost": 5580.55,
    "revenue": 10018.23
  },
  {
    "date": "2026-02-17",
    "purchaseCost": 3958.63,
    "revenue": 6933.94
  },
  {
    "date": "2026-02-18",
    "purchaseCost": 6018.32,
    "revenue": 11200.78
  },
  {
    "date": "2026-02-19",
    "purchaseCost": 2422.99,
    "revenue": 4517.87
  },
  {
    "date": "2026-02-20",
    "purchaseCost": 2216.57,
    "revenue": 4267.86
  },
  {
    "date": "2026-02-21",
    "purchaseCost": 4207.71,
    "revenue": 7616.1
  },
  {
    "date": "2026-02-22",
    "purchaseCost": 1554.07,
    "revenue": 2725.87
  },
  {
    "date": "2026-02-23",
    "purchaseCost": 1697.95,
    "revenue": 3067.89
  },
  {
    "date": "2026-02-24",
    "purchaseCost": 1674.52,
    "revenue": 3214.31
  },
  {
    "date": "2026-02-25",
    "purchaseCost": 7467.15,
    "revenue": 13441.08
  },
  {
    "date": "2026-02-26",
    "purchaseCost": 10067.24,
    "revenue": 17964.79
  },
  {
    "date": "2026-02-27",
    "purchaseCost": 3937.89,
    "revenue": 6981.27
  },
  {
    "date": "2026-02-28",
    "purchaseCost": 1120.97,
    "revenue": 2146.44
  },
  {
    "date": "2026-03-01",
    "purchaseCost": 2222.51,
    "revenue": 4180.35
  },
  {
    "date": "2026-03-02",
    "purchaseCost": 7164.74,
    "revenue": 12062.44
  },
  {
    "date": "2026-03-03",
    "purchaseCost": 6888.59,
    "revenue": 12225.04
  },
  {
    "date": "2026-03-04",
    "purchaseCost": 6000.23,
    "revenue": 10898.26
  },
  {
    "date": "2026-03-05",
    "purchaseCost": 902.46,
    "revenue": 1794.64
  },
  {
    "date": "2026-03-06",
    "purchaseCost": 5411.05,
    "revenue": 9942.88
  },
  {
    "date": "2026-03-07",
    "purchaseCost": 5954.23,
    "revenue": 10984.87
  },
  {
    "date": "2026-03-08",
    "purchaseCost": 3844.64,
    "revenue": 6776.6
  },
  {
    "date": "2026-03-09",
    "purchaseCost": 6727.99,
    "revenue": 12285.74
  },
  {
    "date": "2026-03-10",
    "purchaseCost": 16063.92,
    "revenue": 28020.05
  },
  {
    "date": "2026-03-11",
    "purchaseCost": 8797.63,
    "revenue": 15538.4
  },
  {
    "date": "2026-03-12",
    "purchaseCost": 6277.37,
    "revenue": 10808.92
  },
  {
    "date": "2026-03-13",
    "purchaseCost": 6703.92,
    "revenue": 11597.1
  },
  {
    "date": "2026-03-14",
    "purchaseCost": 5207.4,
    "revenue": 9637.47
  },
  {
    "date": "2026-03-15",
    "purchaseCost": 10010.72,
    "revenue": 17924.1
  },
  {
    "date": "2026-03-16",
    "purchaseCost": 6484.75,
    "revenue": 11390.16
  },
  {
    "date": "2026-03-17",
    "purchaseCost": 5261.64,
    "revenue": 9457.13
  },
  {
    "date": "2026-03-18",
    "purchaseCost": 6388.95,
    "revenue": 11069.67
  },
  {
    "date": "2026-03-19",
    "purchaseCost": 4934.75,
    "revenue": 8768.8
  },
  {
    "date": "2026-03-20",
    "purchaseCost": 4586.75,
    "revenue": 8437.52
  },
  {
    "date": "2026-03-21",
    "purchaseCost": 1717.67,
    "revenue": 3101.79
  },
  {
    "date": "2026-03-22",
    "purchaseCost": 3091.21,
    "revenue": 5464.3
  },
  {
    "date": "2026-03-23",
    "purchaseCost": 2197.67,
    "revenue": 3975.91
  },
  {
    "date": "2026-03-24",
    "purchaseCost": 7517.88,
    "revenue": 13367.71
  },
  {
    "date": "2026-03-25",
    "purchaseCost": 3000.29,
    "revenue": 5722.29
  },
  {
    "date": "2026-03-26",
    "purchaseCost": 5225.17,
    "revenue": 8843.76
  },
  {
    "date": "2026-03-27",
    "purchaseCost": 1876.99,
    "revenue": 3177.68
  },
  {
    "date": "2026-03-28",
    "purchaseCost": 3175.5,
    "revenue": 5575.91
  },
  {
    "date": "2026-03-29",
    "purchaseCost": 13729.73,
    "revenue": 24078.17
  },
  {
    "date": "2026-03-30",
    "purchaseCost": 4547.52,
    "revenue": 8454.58
  },
  {
    "date": "2026-03-31",
    "purchaseCost": 1705.91,
    "revenue": 3156.25
  },
  {
    "date": "2026-04-01",
    "purchaseCost": 3921.44,
    "revenue": 6729.48
  },
  {
    "date": "2026-04-02",
    "purchaseCost": 803.02,
    "revenue": 1550.9
  },
  {
    "date": "2026-04-03",
    "purchaseCost": 10043.94,
    "revenue": 17651.78
  },
  {
    "date": "2026-04-04",
    "purchaseCost": 7473.53,
    "revenue": 12774.58
  },
  {
    "date": "2026-04-05",
    "purchaseCost": 5134.57,
    "revenue": 8690.57
  },
  {
    "date": "2026-04-06",
    "purchaseCost": 4713.56,
    "revenue": 8586.63
  },
  {
    "date": "2026-04-07",
    "purchaseCost": 2765.55,
    "revenue": 5038.39
  },
  {
    "date": "2026-04-08",
    "purchaseCost": 5768.53,
    "revenue": 10286.19
  },
  {
    "date": "2026-04-09",
    "purchaseCost": 12223.18,
    "revenue": 20430.53
  },
  {
    "date": "2026-04-10",
    "purchaseCost": 5695.24,
    "revenue": 10163.75
  },
  {
    "date": "2026-04-11",
    "purchaseCost": 5795.93,
    "revenue": 10466.11
  },
  {
    "date": "2026-04-12",
    "purchaseCost": 2869.36,
    "revenue": 5048.22
  },
  {
    "date": "2026-04-13",
    "purchaseCost": 2346.21,
    "revenue": 3874.11
  },
  {
    "date": "2026-04-14",
    "purchaseCost": 4732.39,
    "revenue": 8496.45
  },
  {
    "date": "2026-04-15",
    "purchaseCost": 9266.96,
    "revenue": 16050.44
  },
  {
    "date": "2026-04-16",
    "purchaseCost": 5037.11,
    "revenue": 9089.27
  },
  {
    "date": "2026-04-17",
    "purchaseCost": 6438.42,
    "revenue": 11226.78
  },
  {
    "date": "2026-04-18",
    "purchaseCost": 4342,
    "revenue": 7753.58
  },
  {
    "date": "2026-04-19",
    "purchaseCost": 11933.92,
    "revenue": 21019.68
  },
  {
    "date": "2026-04-20",
    "purchaseCost": 6400.35,
    "revenue": 11482.17
  },
  {
    "date": "2026-04-21",
    "purchaseCost": 19002.76,
    "revenue": 32080.44
  },
  {
    "date": "2026-04-22",
    "purchaseCost": 8023.4,
    "revenue": 13846.6
  },
  {
    "date": "2026-04-23",
    "purchaseCost": 2193.55,
    "revenue": 4010.73
  },
  {
    "date": "2026-04-24",
    "purchaseCost": 5566.73,
    "revenue": 10372.37
  },
  {
    "date": "2026-04-25",
    "purchaseCost": 6482.33,
    "revenue": 11474.14
  },
  {
    "date": "2026-04-26",
    "purchaseCost": 9524.83,
    "revenue": 16917.41
  },
  {
    "date": "2026-04-27",
    "purchaseCost": 8869.07,
    "revenue": 15484.1
  },
  {
    "date": "2026-04-28",
    "purchaseCost": 5720.41,
    "revenue": 10780.37
  },
  {
    "date": "2026-04-29",
    "purchaseCost": 3443.16,
    "revenue": 6164.62
  },
  {
    "date": "2026-04-30",
    "purchaseCost": 6644.14,
    "revenue": 11548.24
  },
  {
    "date": "2026-05-01",
    "purchaseCost": 14741.91,
    "revenue": 25246.93
  },
  {
    "date": "2026-05-02",
    "purchaseCost": 14593.2,
    "revenue": 26196.09
  },
  {
    "date": "2026-05-03",
    "purchaseCost": 4680.62,
    "revenue": 8727.66
  },
  {
    "date": "2026-05-04",
    "purchaseCost": 9836.87,
    "revenue": 17685.35
  },
  {
    "date": "2026-05-05",
    "purchaseCost": 15195.04,
    "revenue": 26817.88
  },
  {
    "date": "2026-05-06",
    "purchaseCost": 3987.48,
    "revenue": 7386.62
  },
  {
    "date": "2026-05-07",
    "purchaseCost": 9737.67,
    "revenue": 16787.07
  },
  {
    "date": "2026-05-08",
    "purchaseCost": 13665.75,
    "revenue": 23170.46
  },
  {
    "date": "2026-05-09",
    "purchaseCost": 11174.09,
    "revenue": 19116.49
  },
  {
    "date": "2026-05-10",
    "purchaseCost": 8880.56,
    "revenue": 15948.17
  },
  {
    "date": "2026-05-11",
    "purchaseCost": 5829.94,
    "revenue": 10617.9
  },
  {
    "date": "2026-05-12",
    "purchaseCost": 8133.96,
    "revenue": 13997.8
  },
  {
    "date": "2026-05-13",
    "purchaseCost": 8190.2,
    "revenue": 14330.37
  },
  {
    "date": "2026-05-14",
    "purchaseCost": 9753.21,
    "revenue": 17394.05
  },
  {
    "date": "2026-05-15",
    "purchaseCost": 15172.75,
    "revenue": 27289.33
  },
  {
    "date": "2026-05-16",
    "purchaseCost": 4099.22,
    "revenue": 7701.81
  },
  {
    "date": "2026-05-17",
    "purchaseCost": 7519.49,
    "revenue": 13065.17
  },
  {
    "date": "2026-05-18",
    "purchaseCost": 8891.11,
    "revenue": 16647.29
  },
  {
    "date": "2026-05-19",
    "purchaseCost": 8311.45,
    "revenue": 14447.39
  },
  {
    "date": "2026-05-20",
    "purchaseCost": 587.52,
    "revenue": 1136.59
  }
];
