// Auto-generated by scripts/updateData.js — last update: 2026-05-19
// SK: daily margin data (EUR). purchaseCost = nákupní cena (0 = data není k dispozici), revenue = tržby bez DPH.

export interface MarginDailyRecord {
  date: string;        // ISO "2025-05-25"
  purchaseCost: number; // nákupní cena (součet za den) — pro SK vždy 0
  revenue: number;      // tržby bez DPH (součet za den)
}

export const marginDataSK: MarginDailyRecord[] = [
  {
    "date": "2024-03-26",
    "purchaseCost": 0,
    "revenue": 33.56
  },
  {
    "date": "2024-04-17",
    "purchaseCost": 0,
    "revenue": 23.43
  },
  {
    "date": "2024-04-24",
    "purchaseCost": 0,
    "revenue": 55.19
  },
  {
    "date": "2024-04-26",
    "purchaseCost": 0,
    "revenue": 65.6
  },
  {
    "date": "2024-06-02",
    "purchaseCost": 0,
    "revenue": 4.93
  },
  {
    "date": "2024-06-07",
    "purchaseCost": 0,
    "revenue": 39.62
  },
  {
    "date": "2024-06-10",
    "purchaseCost": 0,
    "revenue": 71.68
  },
  {
    "date": "2024-06-11",
    "purchaseCost": 0,
    "revenue": 29.41
  },
  {
    "date": "2024-06-14",
    "purchaseCost": 0,
    "revenue": 50.06
  },
  {
    "date": "2024-06-15",
    "purchaseCost": 0,
    "revenue": 43.47
  },
  {
    "date": "2024-06-19",
    "purchaseCost": 0,
    "revenue": 87.86
  },
  {
    "date": "2024-06-20",
    "purchaseCost": 0,
    "revenue": 76.33
  },
  {
    "date": "2024-06-23",
    "purchaseCost": 0,
    "revenue": 62.78
  },
  {
    "date": "2024-06-26",
    "purchaseCost": 0,
    "revenue": 36.62
  },
  {
    "date": "2024-07-08",
    "purchaseCost": 0,
    "revenue": 107.08
  },
  {
    "date": "2024-07-12",
    "purchaseCost": 0,
    "revenue": 33.48
  },
  {
    "date": "2024-07-14",
    "purchaseCost": 0,
    "revenue": 46.82
  },
  {
    "date": "2024-07-15",
    "purchaseCost": 0,
    "revenue": 111.45
  },
  {
    "date": "2024-07-16",
    "purchaseCost": 0,
    "revenue": 10.56
  },
  {
    "date": "2024-07-19",
    "purchaseCost": 0,
    "revenue": 71.26
  },
  {
    "date": "2024-07-26",
    "purchaseCost": 0,
    "revenue": 185.9
  },
  {
    "date": "2024-08-11",
    "purchaseCost": 0,
    "revenue": 139.92
  },
  {
    "date": "2024-08-18",
    "purchaseCost": 0,
    "revenue": 35.81
  },
  {
    "date": "2024-08-19",
    "purchaseCost": 0,
    "revenue": 76.95
  },
  {
    "date": "2024-08-27",
    "purchaseCost": 0,
    "revenue": 86.32
  },
  {
    "date": "2024-08-30",
    "purchaseCost": 0,
    "revenue": 126.56
  },
  {
    "date": "2024-08-31",
    "purchaseCost": 0,
    "revenue": 86.46
  },
  {
    "date": "2024-09-01",
    "purchaseCost": 0,
    "revenue": 124.52
  },
  {
    "date": "2024-09-05",
    "purchaseCost": 0,
    "revenue": 106.78
  },
  {
    "date": "2024-09-08",
    "purchaseCost": 0,
    "revenue": 106.07
  },
  {
    "date": "2024-09-09",
    "purchaseCost": 0,
    "revenue": 63.54
  },
  {
    "date": "2024-09-12",
    "purchaseCost": 0,
    "revenue": 44.42
  },
  {
    "date": "2024-09-13",
    "purchaseCost": 0,
    "revenue": 26.21
  },
  {
    "date": "2024-09-15",
    "purchaseCost": 0,
    "revenue": 69.48
  },
  {
    "date": "2024-09-16",
    "purchaseCost": 0,
    "revenue": 90.92
  },
  {
    "date": "2024-09-20",
    "purchaseCost": 0,
    "revenue": 59.07
  },
  {
    "date": "2024-09-21",
    "purchaseCost": 0,
    "revenue": 78.51
  },
  {
    "date": "2024-09-22",
    "purchaseCost": 0,
    "revenue": 27.75
  },
  {
    "date": "2024-09-23",
    "purchaseCost": 0,
    "revenue": 85.8
  },
  {
    "date": "2024-09-24",
    "purchaseCost": 0,
    "revenue": 259
  },
  {
    "date": "2024-09-25",
    "purchaseCost": 0,
    "revenue": 52.89
  },
  {
    "date": "2024-09-26",
    "purchaseCost": 0,
    "revenue": 60.96
  },
  {
    "date": "2024-09-27",
    "purchaseCost": 0,
    "revenue": 44.42
  },
  {
    "date": "2024-09-29",
    "purchaseCost": 0,
    "revenue": 20.15
  },
  {
    "date": "2024-09-30",
    "purchaseCost": 0,
    "revenue": 135.66
  },
  {
    "date": "2024-10-01",
    "purchaseCost": 0,
    "revenue": 58.93
  },
  {
    "date": "2024-10-02",
    "purchaseCost": 0,
    "revenue": 59.76
  },
  {
    "date": "2024-10-04",
    "purchaseCost": 0,
    "revenue": 93.59
  },
  {
    "date": "2024-10-05",
    "purchaseCost": 0,
    "revenue": 182.63
  },
  {
    "date": "2024-10-07",
    "purchaseCost": 0,
    "revenue": 59.28
  },
  {
    "date": "2024-10-10",
    "purchaseCost": 0,
    "revenue": 290.81
  },
  {
    "date": "2024-10-12",
    "purchaseCost": 0,
    "revenue": 170.28
  },
  {
    "date": "2024-10-13",
    "purchaseCost": 0,
    "revenue": 89.09
  },
  {
    "date": "2024-10-16",
    "purchaseCost": 0,
    "revenue": 30.71
  },
  {
    "date": "2024-10-18",
    "purchaseCost": 0,
    "revenue": 123.19
  },
  {
    "date": "2024-10-19",
    "purchaseCost": 0,
    "revenue": 68.36
  },
  {
    "date": "2024-10-24",
    "purchaseCost": 0,
    "revenue": 83.73
  },
  {
    "date": "2024-10-26",
    "purchaseCost": 0,
    "revenue": 59.07
  },
  {
    "date": "2024-10-28",
    "purchaseCost": 0,
    "revenue": 66.96
  },
  {
    "date": "2024-10-29",
    "purchaseCost": 0,
    "revenue": 65.03
  },
  {
    "date": "2024-10-30",
    "purchaseCost": 0,
    "revenue": 14.82
  },
  {
    "date": "2024-11-01",
    "purchaseCost": 0,
    "revenue": 26.45
  },
  {
    "date": "2024-11-07",
    "purchaseCost": 0,
    "revenue": 92.95
  },
  {
    "date": "2024-11-09",
    "purchaseCost": 0,
    "revenue": 181.27
  },
  {
    "date": "2024-11-12",
    "purchaseCost": 0,
    "revenue": 134.75
  },
  {
    "date": "2024-11-13",
    "purchaseCost": 0,
    "revenue": 23.13
  },
  {
    "date": "2024-11-14",
    "purchaseCost": 0,
    "revenue": 67.01
  },
  {
    "date": "2024-11-15",
    "purchaseCost": 0,
    "revenue": 35.98
  },
  {
    "date": "2024-11-18",
    "purchaseCost": 0,
    "revenue": 117.66
  },
  {
    "date": "2024-11-19",
    "purchaseCost": 0,
    "revenue": 21.13
  },
  {
    "date": "2024-11-21",
    "purchaseCost": 0,
    "revenue": 29.32
  },
  {
    "date": "2024-11-23",
    "purchaseCost": 0,
    "revenue": 52.58
  },
  {
    "date": "2024-11-24",
    "purchaseCost": 0,
    "revenue": 151.35
  },
  {
    "date": "2024-11-25",
    "purchaseCost": 0,
    "revenue": 63.67
  },
  {
    "date": "2024-11-26",
    "purchaseCost": 0,
    "revenue": 161.36
  },
  {
    "date": "2024-11-27",
    "purchaseCost": 0,
    "revenue": 47.28
  },
  {
    "date": "2024-11-28",
    "purchaseCost": 0,
    "revenue": 100.33
  },
  {
    "date": "2024-11-29",
    "purchaseCost": 0,
    "revenue": 130.65
  },
  {
    "date": "2024-12-03",
    "purchaseCost": 0,
    "revenue": 104.26
  },
  {
    "date": "2024-12-04",
    "purchaseCost": 0,
    "revenue": 119.82
  },
  {
    "date": "2024-12-05",
    "purchaseCost": 0,
    "revenue": 209.14
  },
  {
    "date": "2024-12-06",
    "purchaseCost": 0,
    "revenue": 59.79
  },
  {
    "date": "2024-12-07",
    "purchaseCost": 0,
    "revenue": 65.59
  },
  {
    "date": "2024-12-08",
    "purchaseCost": 0,
    "revenue": 34.09
  },
  {
    "date": "2024-12-09",
    "purchaseCost": 0,
    "revenue": 67.9
  },
  {
    "date": "2024-12-10",
    "purchaseCost": 0,
    "revenue": 26.19
  },
  {
    "date": "2024-12-11",
    "purchaseCost": 0,
    "revenue": 66.54
  },
  {
    "date": "2024-12-13",
    "purchaseCost": 0,
    "revenue": 38.96
  },
  {
    "date": "2024-12-14",
    "purchaseCost": 0,
    "revenue": 247.66
  },
  {
    "date": "2024-12-15",
    "purchaseCost": 0,
    "revenue": 77.04
  },
  {
    "date": "2024-12-16",
    "purchaseCost": 0,
    "revenue": 13.56
  },
  {
    "date": "2024-12-17",
    "purchaseCost": 0,
    "revenue": 12.73
  },
  {
    "date": "2024-12-18",
    "purchaseCost": 0,
    "revenue": 29.58
  },
  {
    "date": "2024-12-27",
    "purchaseCost": 0,
    "revenue": 48.25
  },
  {
    "date": "2024-12-29",
    "purchaseCost": 0,
    "revenue": 65.65
  },
  {
    "date": "2025-01-07",
    "purchaseCost": 0,
    "revenue": 49.15
  },
  {
    "date": "2025-01-09",
    "purchaseCost": 0,
    "revenue": 147.59
  },
  {
    "date": "2025-01-10",
    "purchaseCost": 0,
    "revenue": 29.2
  },
  {
    "date": "2025-01-11",
    "purchaseCost": 0,
    "revenue": 60.09
  },
  {
    "date": "2025-01-14",
    "purchaseCost": 0,
    "revenue": 52.73
  },
  {
    "date": "2025-01-16",
    "purchaseCost": 0,
    "revenue": 101.53
  },
  {
    "date": "2025-01-17",
    "purchaseCost": 0,
    "revenue": 70.08
  },
  {
    "date": "2025-01-21",
    "purchaseCost": 0,
    "revenue": 49.68
  },
  {
    "date": "2025-01-22",
    "purchaseCost": 0,
    "revenue": 82.58
  },
  {
    "date": "2025-01-23",
    "purchaseCost": 0,
    "revenue": 62.61
  },
  {
    "date": "2025-01-24",
    "purchaseCost": 0,
    "revenue": 63.58
  },
  {
    "date": "2025-01-25",
    "purchaseCost": 0,
    "revenue": 30.75
  },
  {
    "date": "2025-01-26",
    "purchaseCost": 0,
    "revenue": 71.16
  },
  {
    "date": "2025-01-27",
    "purchaseCost": 0,
    "revenue": 189.52
  },
  {
    "date": "2025-01-28",
    "purchaseCost": 0,
    "revenue": 182.38
  },
  {
    "date": "2025-01-30",
    "purchaseCost": 0,
    "revenue": 145.97
  },
  {
    "date": "2025-02-01",
    "purchaseCost": 0,
    "revenue": 35.89
  },
  {
    "date": "2025-02-02",
    "purchaseCost": 0,
    "revenue": 28.8
  },
  {
    "date": "2025-02-03",
    "purchaseCost": 0,
    "revenue": 82.15
  },
  {
    "date": "2025-02-04",
    "purchaseCost": 0,
    "revenue": 127.03
  },
  {
    "date": "2025-02-05",
    "purchaseCost": 0,
    "revenue": 87.4
  },
  {
    "date": "2025-02-06",
    "purchaseCost": 0,
    "revenue": 209.04
  },
  {
    "date": "2025-02-09",
    "purchaseCost": 0,
    "revenue": 80.5
  },
  {
    "date": "2025-02-10",
    "purchaseCost": 0,
    "revenue": 33.01
  },
  {
    "date": "2025-02-11",
    "purchaseCost": 0,
    "revenue": 46.57
  },
  {
    "date": "2025-02-12",
    "purchaseCost": 0,
    "revenue": 36.87
  },
  {
    "date": "2025-02-13",
    "purchaseCost": 0,
    "revenue": 147.7
  },
  {
    "date": "2025-02-15",
    "purchaseCost": 0,
    "revenue": 185.08
  },
  {
    "date": "2025-02-16",
    "purchaseCost": 0,
    "revenue": 74.99
  },
  {
    "date": "2025-02-18",
    "purchaseCost": 0,
    "revenue": 59.48
  },
  {
    "date": "2025-02-19",
    "purchaseCost": 0,
    "revenue": 207.04
  },
  {
    "date": "2025-02-20",
    "purchaseCost": 0,
    "revenue": 95.24
  },
  {
    "date": "2025-02-22",
    "purchaseCost": 0,
    "revenue": 129.44
  },
  {
    "date": "2025-02-24",
    "purchaseCost": 0,
    "revenue": 58.61
  },
  {
    "date": "2025-02-25",
    "purchaseCost": 0,
    "revenue": 74.34
  },
  {
    "date": "2025-02-28",
    "purchaseCost": 0,
    "revenue": 31.24
  },
  {
    "date": "2025-03-01",
    "purchaseCost": 0,
    "revenue": 73.61
  },
  {
    "date": "2025-03-02",
    "purchaseCost": 0,
    "revenue": 53.51
  },
  {
    "date": "2025-03-03",
    "purchaseCost": 0,
    "revenue": 143.97
  },
  {
    "date": "2025-03-04",
    "purchaseCost": 0,
    "revenue": 141.84
  },
  {
    "date": "2025-03-06",
    "purchaseCost": 0,
    "revenue": 269.09
  },
  {
    "date": "2025-03-08",
    "purchaseCost": 0,
    "revenue": 35.97
  },
  {
    "date": "2025-03-10",
    "purchaseCost": 0,
    "revenue": 69.38
  },
  {
    "date": "2025-03-12",
    "purchaseCost": 0,
    "revenue": 101.47
  },
  {
    "date": "2025-03-13",
    "purchaseCost": 0,
    "revenue": 76.05
  },
  {
    "date": "2025-03-14",
    "purchaseCost": 0,
    "revenue": 145.94
  },
  {
    "date": "2025-03-15",
    "purchaseCost": 0,
    "revenue": 126.37
  },
  {
    "date": "2025-03-16",
    "purchaseCost": 0,
    "revenue": 168.57
  },
  {
    "date": "2025-03-18",
    "purchaseCost": 0,
    "revenue": 28.07
  },
  {
    "date": "2025-03-19",
    "purchaseCost": 0,
    "revenue": 45.93
  },
  {
    "date": "2025-03-20",
    "purchaseCost": 0,
    "revenue": 73.66
  },
  {
    "date": "2025-03-22",
    "purchaseCost": 0,
    "revenue": 73.84
  },
  {
    "date": "2025-03-23",
    "purchaseCost": 0,
    "revenue": 51.71
  },
  {
    "date": "2025-03-24",
    "purchaseCost": 0,
    "revenue": 102.44
  },
  {
    "date": "2025-03-25",
    "purchaseCost": 0,
    "revenue": 104.15
  },
  {
    "date": "2025-03-26",
    "purchaseCost": 0,
    "revenue": 52.39
  },
  {
    "date": "2025-03-27",
    "purchaseCost": 0,
    "revenue": 197.96
  },
  {
    "date": "2025-03-31",
    "purchaseCost": 0,
    "revenue": 93.61
  },
  {
    "date": "2025-04-01",
    "purchaseCost": 0,
    "revenue": 299.63
  },
  {
    "date": "2025-04-02",
    "purchaseCost": 0,
    "revenue": 58.31
  },
  {
    "date": "2025-04-03",
    "purchaseCost": 0,
    "revenue": 79.36
  },
  {
    "date": "2025-04-04",
    "purchaseCost": 0,
    "revenue": 73.68
  },
  {
    "date": "2025-04-06",
    "purchaseCost": 0,
    "revenue": 96.8
  },
  {
    "date": "2025-04-07",
    "purchaseCost": 0,
    "revenue": 169.79
  },
  {
    "date": "2025-04-08",
    "purchaseCost": 0,
    "revenue": 152.87
  },
  {
    "date": "2025-04-09",
    "purchaseCost": 0,
    "revenue": 31.24
  },
  {
    "date": "2025-04-12",
    "purchaseCost": 0,
    "revenue": 31.24
  },
  {
    "date": "2025-04-13",
    "purchaseCost": 0,
    "revenue": 11.31
  },
  {
    "date": "2025-04-14",
    "purchaseCost": 0,
    "revenue": 54.97
  },
  {
    "date": "2025-04-15",
    "purchaseCost": 0,
    "revenue": 51.37
  },
  {
    "date": "2025-04-16",
    "purchaseCost": 0,
    "revenue": 77.33
  },
  {
    "date": "2025-04-17",
    "purchaseCost": 0,
    "revenue": 111.59
  },
  {
    "date": "2025-04-18",
    "purchaseCost": 0,
    "revenue": 82.55
  },
  {
    "date": "2025-04-19",
    "purchaseCost": 0,
    "revenue": 73.6
  },
  {
    "date": "2025-04-20",
    "purchaseCost": 0,
    "revenue": 32.5
  },
  {
    "date": "2025-04-21",
    "purchaseCost": 0,
    "revenue": 24.41
  },
  {
    "date": "2025-04-22",
    "purchaseCost": 0,
    "revenue": 43.58
  },
  {
    "date": "2025-04-25",
    "purchaseCost": 0,
    "revenue": 69.97
  },
  {
    "date": "2025-04-26",
    "purchaseCost": 0,
    "revenue": 69.2
  },
  {
    "date": "2025-04-27",
    "purchaseCost": 0,
    "revenue": 72.62
  },
  {
    "date": "2025-04-28",
    "purchaseCost": 0,
    "revenue": 63.7
  },
  {
    "date": "2025-04-29",
    "purchaseCost": 0,
    "revenue": 45.92
  },
  {
    "date": "2025-05-01",
    "purchaseCost": 0,
    "revenue": 53.94
  },
  {
    "date": "2025-05-04",
    "purchaseCost": 0,
    "revenue": 131.7
  },
  {
    "date": "2025-05-05",
    "purchaseCost": 0,
    "revenue": 60.74
  },
  {
    "date": "2025-05-06",
    "purchaseCost": 0,
    "revenue": 70.8
  },
  {
    "date": "2025-05-07",
    "purchaseCost": 0,
    "revenue": 30.24
  },
  {
    "date": "2025-05-09",
    "purchaseCost": 0,
    "revenue": 32.23
  },
  {
    "date": "2025-05-10",
    "purchaseCost": 0,
    "revenue": 28.31
  },
  {
    "date": "2025-05-12",
    "purchaseCost": 0,
    "revenue": 47.74
  },
  {
    "date": "2025-05-13",
    "purchaseCost": 0,
    "revenue": 363.19
  },
  {
    "date": "2025-05-18",
    "purchaseCost": 197.82,
    "revenue": 301.99
  },
  {
    "date": "2025-05-20",
    "purchaseCost": 184.68,
    "revenue": 272.8
  },
  {
    "date": "2025-05-21",
    "purchaseCost": 92.72,
    "revenue": 143.68
  },
  {
    "date": "2025-05-22",
    "purchaseCost": 68.86,
    "revenue": 97.02
  },
  {
    "date": "2025-05-25",
    "purchaseCost": 103.13,
    "revenue": 137.41
  },
  {
    "date": "2025-05-26",
    "purchaseCost": 83.47,
    "revenue": 122.86
  },
  {
    "date": "2025-05-27",
    "purchaseCost": 89.55,
    "revenue": 139.78
  },
  {
    "date": "2025-05-28",
    "purchaseCost": 18.43,
    "revenue": 31.65
  },
  {
    "date": "2025-05-29",
    "purchaseCost": 19.44,
    "revenue": 33.03
  },
  {
    "date": "2025-05-30",
    "purchaseCost": 20.03,
    "revenue": 34.14
  },
  {
    "date": "2025-05-31",
    "purchaseCost": 122.86,
    "revenue": 181.43
  },
  {
    "date": "2025-06-02",
    "purchaseCost": 46.07,
    "revenue": 70.17
  },
  {
    "date": "2025-06-05",
    "purchaseCost": 10.63,
    "revenue": 19.28
  },
  {
    "date": "2025-06-06",
    "purchaseCost": 46.83,
    "revenue": 65.22
  },
  {
    "date": "2025-06-08",
    "purchaseCost": 14.44,
    "revenue": 25.12
  },
  {
    "date": "2025-06-09",
    "purchaseCost": 30.01,
    "revenue": 49.67
  },
  {
    "date": "2025-06-11",
    "purchaseCost": 26.87,
    "revenue": 32.91
  },
  {
    "date": "2025-06-12",
    "purchaseCost": 102.62,
    "revenue": 164.99
  },
  {
    "date": "2025-06-14",
    "purchaseCost": 37,
    "revenue": 54.56
  },
  {
    "date": "2025-06-16",
    "purchaseCost": 158.1,
    "revenue": 261.04
  },
  {
    "date": "2025-06-18",
    "purchaseCost": 23.83,
    "revenue": 39.07
  },
  {
    "date": "2025-06-20",
    "purchaseCost": 53.69,
    "revenue": 79.2
  },
  {
    "date": "2025-06-21",
    "purchaseCost": 90.26,
    "revenue": 137.54
  },
  {
    "date": "2025-06-23",
    "purchaseCost": 132.35,
    "revenue": 205.25
  },
  {
    "date": "2025-06-24",
    "purchaseCost": 0,
    "revenue": 267.88
  },
  {
    "date": "2025-06-25",
    "purchaseCost": 57.98,
    "revenue": 85.59
  },
  {
    "date": "2025-06-26",
    "purchaseCost": 21.35,
    "revenue": 31.51
  },
  {
    "date": "2025-06-27",
    "purchaseCost": 53.96,
    "revenue": 79.59
  },
  {
    "date": "2025-06-29",
    "purchaseCost": 52.38,
    "revenue": 85.87
  },
  {
    "date": "2025-07-01",
    "purchaseCost": 37.63,
    "revenue": 67.1
  },
  {
    "date": "2025-07-03",
    "purchaseCost": 22.05,
    "revenue": 40.29
  },
  {
    "date": "2025-07-04",
    "purchaseCost": 249.89,
    "revenue": 393.02
  },
  {
    "date": "2025-07-05",
    "purchaseCost": 107.38,
    "revenue": 160.12
  },
  {
    "date": "2025-07-06",
    "purchaseCost": 28.55,
    "revenue": 47.54
  },
  {
    "date": "2025-07-08",
    "purchaseCost": 75.43,
    "revenue": 118.92
  },
  {
    "date": "2025-07-09",
    "purchaseCost": 109.17,
    "revenue": 173.19
  },
  {
    "date": "2025-07-10",
    "purchaseCost": 46.28,
    "revenue": 69.71
  },
  {
    "date": "2025-07-13",
    "purchaseCost": 44.48,
    "revenue": 74.2
  },
  {
    "date": "2025-07-15",
    "purchaseCost": 61.91,
    "revenue": 102.76
  },
  {
    "date": "2025-07-16",
    "purchaseCost": 43.36,
    "revenue": 69.04
  },
  {
    "date": "2025-07-17",
    "purchaseCost": 17.09,
    "revenue": 33.45
  },
  {
    "date": "2025-07-18",
    "purchaseCost": 36.64,
    "revenue": 60.05
  },
  {
    "date": "2025-07-20",
    "purchaseCost": 86.44,
    "revenue": 145.35
  },
  {
    "date": "2025-07-21",
    "purchaseCost": 136.34,
    "revenue": 210.31
  },
  {
    "date": "2025-07-23",
    "purchaseCost": 31.44,
    "revenue": 55.72
  },
  {
    "date": "2025-07-24",
    "purchaseCost": 135.32,
    "revenue": 211.48
  },
  {
    "date": "2025-07-27",
    "purchaseCost": 57.09,
    "revenue": 100.64
  },
  {
    "date": "2025-07-29",
    "purchaseCost": 58.29,
    "revenue": 95.56
  },
  {
    "date": "2025-07-31",
    "purchaseCost": 45.15,
    "revenue": 75.29
  },
  {
    "date": "2025-08-01",
    "purchaseCost": 0,
    "revenue": 374.75
  },
  {
    "date": "2025-08-02",
    "purchaseCost": 16.53,
    "revenue": 31.27
  },
  {
    "date": "2025-08-03",
    "purchaseCost": 31.64,
    "revenue": 56.02
  },
  {
    "date": "2025-08-04",
    "purchaseCost": 46.2,
    "revenue": 69.42
  },
  {
    "date": "2025-08-05",
    "purchaseCost": 137.14,
    "revenue": 237.18
  },
  {
    "date": "2025-08-06",
    "purchaseCost": 53.24,
    "revenue": 88.17
  },
  {
    "date": "2025-08-08",
    "purchaseCost": 30.66,
    "revenue": 55.69
  },
  {
    "date": "2025-08-10",
    "purchaseCost": 140.21,
    "revenue": 212.44
  },
  {
    "date": "2025-08-12",
    "purchaseCost": 47.16,
    "revenue": 69.61
  },
  {
    "date": "2025-08-14",
    "purchaseCost": 64.97,
    "revenue": 100.99
  },
  {
    "date": "2025-08-16",
    "purchaseCost": 36.7,
    "revenue": 60.48
  },
  {
    "date": "2025-08-17",
    "purchaseCost": 35.13,
    "revenue": 68.39
  },
  {
    "date": "2025-08-18",
    "purchaseCost": 93.43,
    "revenue": 141.81
  },
  {
    "date": "2025-08-19",
    "purchaseCost": 129.77,
    "revenue": 212.69
  },
  {
    "date": "2025-08-21",
    "purchaseCost": 163.14,
    "revenue": 260.23
  },
  {
    "date": "2025-08-24",
    "purchaseCost": 18.69,
    "revenue": 36.07
  },
  {
    "date": "2025-08-27",
    "purchaseCost": 57.31,
    "revenue": 98.13
  },
  {
    "date": "2025-08-28",
    "purchaseCost": 66.25,
    "revenue": 105.04
  },
  {
    "date": "2025-08-29",
    "purchaseCost": 43.47,
    "revenue": 71.27
  },
  {
    "date": "2025-09-02",
    "purchaseCost": 43.91,
    "revenue": 71.98
  },
  {
    "date": "2025-09-03",
    "purchaseCost": 12.23,
    "revenue": 25.46
  },
  {
    "date": "2025-09-04",
    "purchaseCost": 45.9,
    "revenue": 67.71
  },
  {
    "date": "2025-09-06",
    "purchaseCost": 10.27,
    "revenue": 16.83
  },
  {
    "date": "2025-09-08",
    "purchaseCost": 60.3,
    "revenue": 88.94
  },
  {
    "date": "2025-09-10",
    "purchaseCost": 58.54,
    "revenue": 87.67
  },
  {
    "date": "2025-09-11",
    "purchaseCost": 109.22,
    "revenue": 177.3
  },
  {
    "date": "2025-09-18",
    "purchaseCost": 58.65,
    "revenue": 100.7
  },
  {
    "date": "2025-09-20",
    "purchaseCost": 42.34,
    "revenue": 69.4
  },
  {
    "date": "2025-09-21",
    "purchaseCost": 27.64,
    "revenue": 47.42
  },
  {
    "date": "2025-09-22",
    "purchaseCost": 223.77,
    "revenue": 373.41
  },
  {
    "date": "2025-09-23",
    "purchaseCost": 296.81,
    "revenue": 489.27
  },
  {
    "date": "2025-09-24",
    "purchaseCost": 91.75,
    "revenue": 153.86
  },
  {
    "date": "2025-09-25",
    "purchaseCost": 73.99,
    "revenue": 124.01
  },
  {
    "date": "2025-09-26",
    "purchaseCost": 146.81,
    "revenue": 233.77
  },
  {
    "date": "2025-09-27",
    "purchaseCost": 79.68,
    "revenue": 117.59
  },
  {
    "date": "2025-09-28",
    "purchaseCost": 81.97,
    "revenue": 141.36
  },
  {
    "date": "2025-09-29",
    "purchaseCost": 74.16,
    "revenue": 130.96
  },
  {
    "date": "2025-09-30",
    "purchaseCost": 41.47,
    "revenue": 70.11
  },
  {
    "date": "2025-10-02",
    "purchaseCost": 0,
    "revenue": 426.02
  },
  {
    "date": "2025-10-05",
    "purchaseCost": 127.94,
    "revenue": 218.58
  },
  {
    "date": "2025-10-07",
    "purchaseCost": 69.61,
    "revenue": 111.12
  },
  {
    "date": "2025-10-08",
    "purchaseCost": 41.64,
    "revenue": 69.8
  },
  {
    "date": "2025-10-12",
    "purchaseCost": 115.99,
    "revenue": 184.21
  },
  {
    "date": "2025-10-13",
    "purchaseCost": 175.8,
    "revenue": 277.46
  },
  {
    "date": "2025-10-14",
    "purchaseCost": 90.61,
    "revenue": 158.23
  },
  {
    "date": "2025-10-15",
    "purchaseCost": 114.44,
    "revenue": 196.42
  },
  {
    "date": "2025-10-16",
    "purchaseCost": 104.34,
    "revenue": 179.88
  },
  {
    "date": "2025-10-17",
    "purchaseCost": 66,
    "revenue": 113.67
  },
  {
    "date": "2025-10-18",
    "purchaseCost": 123.76,
    "revenue": 208.29
  },
  {
    "date": "2025-10-19",
    "purchaseCost": 62.68,
    "revenue": 104.07
  },
  {
    "date": "2025-10-20",
    "purchaseCost": 132.97,
    "revenue": 211.4
  },
  {
    "date": "2025-10-21",
    "purchaseCost": 18.27,
    "revenue": 35.39
  },
  {
    "date": "2025-10-23",
    "purchaseCost": 15.08,
    "revenue": 28.87
  },
  {
    "date": "2025-10-24",
    "purchaseCost": 109.62,
    "revenue": 167.2
  },
  {
    "date": "2025-10-25",
    "purchaseCost": 43.02,
    "revenue": 76.28
  },
  {
    "date": "2025-10-26",
    "purchaseCost": 121.66,
    "revenue": 187.34
  },
  {
    "date": "2025-10-28",
    "purchaseCost": 18.9,
    "revenue": 34.65
  },
  {
    "date": "2025-11-01",
    "purchaseCost": 23.87,
    "revenue": 44.85
  },
  {
    "date": "2025-11-02",
    "purchaseCost": 62.48,
    "revenue": 99.34
  },
  {
    "date": "2025-11-04",
    "purchaseCost": 41.18,
    "revenue": 68.78
  },
  {
    "date": "2025-11-05",
    "purchaseCost": 47.95,
    "revenue": 88.16
  },
  {
    "date": "2025-11-07",
    "purchaseCost": 21.67,
    "revenue": 36.65
  },
  {
    "date": "2025-11-08",
    "purchaseCost": 356.97,
    "revenue": 564.88
  },
  {
    "date": "2025-11-09",
    "purchaseCost": 101.65,
    "revenue": 169.27
  },
  {
    "date": "2025-11-10",
    "purchaseCost": 166.36,
    "revenue": 270.19
  },
  {
    "date": "2025-11-11",
    "purchaseCost": 135.77,
    "revenue": 233.74
  },
  {
    "date": "2025-11-12",
    "purchaseCost": 125.14,
    "revenue": 211.13
  },
  {
    "date": "2025-11-13",
    "purchaseCost": 32.51,
    "revenue": 59.89
  },
  {
    "date": "2025-11-14",
    "purchaseCost": 19.01,
    "revenue": 35.64
  },
  {
    "date": "2025-11-15",
    "purchaseCost": 62.5,
    "revenue": 111.96
  },
  {
    "date": "2025-11-16",
    "purchaseCost": 104.67,
    "revenue": 176.02
  },
  {
    "date": "2025-11-17",
    "purchaseCost": 83.59,
    "revenue": 139.78
  },
  {
    "date": "2025-11-18",
    "purchaseCost": 92.21,
    "revenue": 167.9
  },
  {
    "date": "2025-11-19",
    "purchaseCost": 193.86,
    "revenue": 314.09
  },
  {
    "date": "2025-11-20",
    "purchaseCost": 52.45,
    "revenue": 99.71
  },
  {
    "date": "2025-11-21",
    "purchaseCost": 35.76,
    "revenue": 68.23
  },
  {
    "date": "2025-11-22",
    "purchaseCost": 29.04,
    "revenue": 48.26
  },
  {
    "date": "2025-11-23",
    "purchaseCost": 301.32,
    "revenue": 499.32
  },
  {
    "date": "2025-11-24",
    "purchaseCost": 263.06,
    "revenue": 412.94
  },
  {
    "date": "2025-11-25",
    "purchaseCost": 84.4,
    "revenue": 148.76
  },
  {
    "date": "2025-11-26",
    "purchaseCost": 79.08,
    "revenue": 135.79
  },
  {
    "date": "2025-11-27",
    "purchaseCost": 90.13,
    "revenue": 147
  },
  {
    "date": "2025-11-28",
    "purchaseCost": 49.2,
    "revenue": 78.91
  },
  {
    "date": "2025-11-29",
    "purchaseCost": 45.7,
    "revenue": 73.22
  },
  {
    "date": "2025-11-30",
    "purchaseCost": 47.28,
    "revenue": 85.85
  },
  {
    "date": "2025-12-01",
    "purchaseCost": 69.12,
    "revenue": 118.7
  },
  {
    "date": "2025-12-02",
    "purchaseCost": 89.62,
    "revenue": 153.45
  },
  {
    "date": "2025-12-04",
    "purchaseCost": 66.36,
    "revenue": 114.59
  },
  {
    "date": "2025-12-05",
    "purchaseCost": 34.32,
    "revenue": 60.19
  },
  {
    "date": "2025-12-06",
    "purchaseCost": 81.05,
    "revenue": 119.61
  },
  {
    "date": "2025-12-07",
    "purchaseCost": 127.37,
    "revenue": 200.92
  },
  {
    "date": "2025-12-08",
    "purchaseCost": 218.74,
    "revenue": 353.46
  },
  {
    "date": "2025-12-09",
    "purchaseCost": 97.16,
    "revenue": 163.76
  },
  {
    "date": "2025-12-10",
    "purchaseCost": 331.55,
    "revenue": 501.88
  },
  {
    "date": "2025-12-11",
    "purchaseCost": 18.15,
    "revenue": 30.93
  },
  {
    "date": "2025-12-12",
    "purchaseCost": 53.97,
    "revenue": 89.64
  },
  {
    "date": "2025-12-13",
    "purchaseCost": 166.9,
    "revenue": 269.76
  },
  {
    "date": "2025-12-14",
    "purchaseCost": 138.38,
    "revenue": 228.8
  },
  {
    "date": "2025-12-15",
    "purchaseCost": 128.16,
    "revenue": 212.18
  },
  {
    "date": "2025-12-16",
    "purchaseCost": 272.58,
    "revenue": 437.56
  },
  {
    "date": "2025-12-17",
    "purchaseCost": 34.26,
    "revenue": 53.56
  },
  {
    "date": "2025-12-29",
    "purchaseCost": 24.85,
    "revenue": 43.18
  },
  {
    "date": "2025-12-30",
    "purchaseCost": 15.14,
    "revenue": 30.24
  },
  {
    "date": "2025-12-31",
    "purchaseCost": 50.54,
    "revenue": 91.9
  },
  {
    "date": "2026-01-01",
    "purchaseCost": 21.14,
    "revenue": 40.07
  },
  {
    "date": "2026-01-03",
    "purchaseCost": 27.6,
    "revenue": 49.41
  },
  {
    "date": "2026-01-04",
    "purchaseCost": 75.42,
    "revenue": 136.85
  },
  {
    "date": "2026-01-05",
    "purchaseCost": 130.38,
    "revenue": 218.36
  },
  {
    "date": "2026-01-06",
    "purchaseCost": 117.93,
    "revenue": 205.97
  },
  {
    "date": "2026-01-07",
    "purchaseCost": 66.52,
    "revenue": 109.66
  },
  {
    "date": "2026-01-08",
    "purchaseCost": 19.04,
    "revenue": 31.22
  },
  {
    "date": "2026-01-09",
    "purchaseCost": 162.79,
    "revenue": 277.46
  },
  {
    "date": "2026-01-10",
    "purchaseCost": 110.44,
    "revenue": 183.77
  },
  {
    "date": "2026-01-11",
    "purchaseCost": 34.01,
    "revenue": 66.58
  },
  {
    "date": "2026-01-12",
    "purchaseCost": 281.56,
    "revenue": 448.15
  },
  {
    "date": "2026-01-13",
    "purchaseCost": 107.56,
    "revenue": 180.76
  },
  {
    "date": "2026-01-14",
    "purchaseCost": 66.33,
    "revenue": 122.25
  },
  {
    "date": "2026-01-16",
    "purchaseCost": 47.4,
    "revenue": 71.15
  },
  {
    "date": "2026-01-18",
    "purchaseCost": 78.96,
    "revenue": 133.88
  },
  {
    "date": "2026-01-20",
    "purchaseCost": 16.62,
    "revenue": 31.71
  },
  {
    "date": "2026-01-21",
    "purchaseCost": 8.34,
    "revenue": 13.67
  },
  {
    "date": "2026-01-22",
    "purchaseCost": 43.08,
    "revenue": 71.52
  },
  {
    "date": "2026-01-23",
    "purchaseCost": 44.47,
    "revenue": 82.47
  },
  {
    "date": "2026-01-24",
    "purchaseCost": 125.25,
    "revenue": 212.57
  },
  {
    "date": "2026-01-25",
    "purchaseCost": 182.57,
    "revenue": 294.87
  },
  {
    "date": "2026-01-26",
    "purchaseCost": 446.25,
    "revenue": 701.74
  },
  {
    "date": "2026-01-27",
    "purchaseCost": 36.3,
    "revenue": 57.71
  },
  {
    "date": "2026-01-28",
    "purchaseCost": 62.38,
    "revenue": 106.41
  },
  {
    "date": "2026-01-30",
    "purchaseCost": 79.62,
    "revenue": 135.17
  },
  {
    "date": "2026-01-31",
    "purchaseCost": 115.99,
    "revenue": 192.6
  },
  {
    "date": "2026-02-01",
    "purchaseCost": 265.46,
    "revenue": 433.25
  },
  {
    "date": "2026-02-02",
    "purchaseCost": 41.01,
    "revenue": 79.25
  },
  {
    "date": "2026-02-03",
    "purchaseCost": 203.42,
    "revenue": 322.6
  },
  {
    "date": "2026-02-04",
    "purchaseCost": 114.34,
    "revenue": 195.11
  },
  {
    "date": "2026-02-05",
    "purchaseCost": 40.53,
    "revenue": 73.04
  },
  {
    "date": "2026-02-06",
    "purchaseCost": 131.01,
    "revenue": 219.77
  },
  {
    "date": "2026-02-07",
    "purchaseCost": 172.04,
    "revenue": 278.2
  },
  {
    "date": "2026-02-08",
    "purchaseCost": 38.79,
    "revenue": 74.41
  },
  {
    "date": "2026-02-09",
    "purchaseCost": 287.46,
    "revenue": 483.78
  },
  {
    "date": "2026-02-10",
    "purchaseCost": 162.28,
    "revenue": 288.02
  },
  {
    "date": "2026-02-11",
    "purchaseCost": 85.61,
    "revenue": 139.47
  },
  {
    "date": "2026-02-12",
    "purchaseCost": 7.86,
    "revenue": 18.31
  },
  {
    "date": "2026-02-13",
    "purchaseCost": 151.75,
    "revenue": 691.09
  },
  {
    "date": "2026-02-14",
    "purchaseCost": 134.21,
    "revenue": 212.29
  },
  {
    "date": "2026-02-15",
    "purchaseCost": 241.12,
    "revenue": 398.25
  },
  {
    "date": "2026-02-16",
    "purchaseCost": 203.57,
    "revenue": 346.77
  },
  {
    "date": "2026-02-17",
    "purchaseCost": 182.57,
    "revenue": 320.88
  },
  {
    "date": "2026-02-18",
    "purchaseCost": 109.72,
    "revenue": 192.89
  },
  {
    "date": "2026-02-19",
    "purchaseCost": 158.94,
    "revenue": 256.51
  },
  {
    "date": "2026-02-20",
    "purchaseCost": 82.99,
    "revenue": 146.18
  },
  {
    "date": "2026-02-21",
    "purchaseCost": 44.04,
    "revenue": 74.06
  },
  {
    "date": "2026-02-22",
    "purchaseCost": 228.68,
    "revenue": 390.38
  },
  {
    "date": "2026-02-23",
    "purchaseCost": 133.82,
    "revenue": 217.73
  },
  {
    "date": "2026-02-24",
    "purchaseCost": 118.41,
    "revenue": 203.23
  },
  {
    "date": "2026-02-25",
    "purchaseCost": 141.44,
    "revenue": 211.69
  },
  {
    "date": "2026-02-26",
    "purchaseCost": 19.23,
    "revenue": 31.53
  },
  {
    "date": "2026-02-27",
    "purchaseCost": 145.64,
    "revenue": 220.43
  },
  {
    "date": "2026-03-01",
    "purchaseCost": 117.34,
    "revenue": 192.62
  },
  {
    "date": "2026-03-02",
    "purchaseCost": 68.24,
    "revenue": 110.25
  },
  {
    "date": "2026-03-03",
    "purchaseCost": 262.04,
    "revenue": 420.04
  },
  {
    "date": "2026-03-04",
    "purchaseCost": 116.9,
    "revenue": 193.28
  },
  {
    "date": "2026-03-05",
    "purchaseCost": 64.39,
    "revenue": 110.31
  },
  {
    "date": "2026-03-06",
    "purchaseCost": 161.83,
    "revenue": 260.15
  },
  {
    "date": "2026-03-07",
    "purchaseCost": 18.29,
    "revenue": 40.82
  },
  {
    "date": "2026-03-08",
    "purchaseCost": 115.58,
    "revenue": 189.44
  },
  {
    "date": "2026-03-09",
    "purchaseCost": 122.35,
    "revenue": 200.85
  },
  {
    "date": "2026-03-10",
    "purchaseCost": 123.46,
    "revenue": 222.76
  },
  {
    "date": "2026-03-11",
    "purchaseCost": 73.4,
    "revenue": 108.3
  },
  {
    "date": "2026-03-12",
    "purchaseCost": 118.2,
    "revenue": 194.97
  },
  {
    "date": "2026-03-13",
    "purchaseCost": 53.53,
    "revenue": 89.33
  },
  {
    "date": "2026-03-14",
    "purchaseCost": 66.16,
    "revenue": 106.18
  },
  {
    "date": "2026-03-15",
    "purchaseCost": 37.8,
    "revenue": 67.39
  },
  {
    "date": "2026-03-16",
    "purchaseCost": 71.98,
    "revenue": 116.63
  },
  {
    "date": "2026-03-17",
    "purchaseCost": 110.19,
    "revenue": 172.57
  },
  {
    "date": "2026-03-18",
    "purchaseCost": 15.29,
    "revenue": 29.53
  },
  {
    "date": "2026-03-19",
    "purchaseCost": 135.23,
    "revenue": 225.56
  },
  {
    "date": "2026-03-20",
    "purchaseCost": 137.31,
    "revenue": 222.02
  },
  {
    "date": "2026-03-21",
    "purchaseCost": 54.25,
    "revenue": 104.55
  },
  {
    "date": "2026-03-22",
    "purchaseCost": 71,
    "revenue": 114.23
  },
  {
    "date": "2026-03-23",
    "purchaseCost": 126.67,
    "revenue": 228.39
  },
  {
    "date": "2026-03-25",
    "purchaseCost": 176.88,
    "revenue": 291.38
  },
  {
    "date": "2026-03-27",
    "purchaseCost": 122.47,
    "revenue": 197.12
  },
  {
    "date": "2026-03-28",
    "purchaseCost": 86,
    "revenue": 139.27
  },
  {
    "date": "2026-03-29",
    "purchaseCost": 158.87,
    "revenue": 269.36
  },
  {
    "date": "2026-03-30",
    "purchaseCost": 133.28,
    "revenue": 225.41
  },
  {
    "date": "2026-03-31",
    "purchaseCost": 46.93,
    "revenue": 72.66
  },
  {
    "date": "2026-04-02",
    "purchaseCost": 93.45,
    "revenue": 141.31
  },
  {
    "date": "2026-04-03",
    "purchaseCost": 71.3,
    "revenue": 105.88
  },
  {
    "date": "2026-04-04",
    "purchaseCost": 107.81,
    "revenue": 170.46
  },
  {
    "date": "2026-04-05",
    "purchaseCost": 60.1,
    "revenue": 98.26
  },
  {
    "date": "2026-04-06",
    "purchaseCost": 160.99,
    "revenue": 266.36
  },
  {
    "date": "2026-04-07",
    "purchaseCost": 52.74,
    "revenue": 92.83
  },
  {
    "date": "2026-04-08",
    "purchaseCost": 165.16,
    "revenue": 269
  },
  {
    "date": "2026-04-09",
    "purchaseCost": 114.48,
    "revenue": 169.98
  },
  {
    "date": "2026-04-11",
    "purchaseCost": 65.06,
    "revenue": 108.14
  },
  {
    "date": "2026-04-12",
    "purchaseCost": 66.4,
    "revenue": 106.42
  },
  {
    "date": "2026-04-13",
    "purchaseCost": 68.07,
    "revenue": 108.26
  },
  {
    "date": "2026-04-14",
    "purchaseCost": 111.32,
    "revenue": 179.64
  },
  {
    "date": "2026-04-15",
    "purchaseCost": 182.47,
    "revenue": 290.62
  },
  {
    "date": "2026-04-16",
    "purchaseCost": 51.69,
    "revenue": 82.22
  },
  {
    "date": "2026-04-17",
    "purchaseCost": 33.95,
    "revenue": 61.1
  },
  {
    "date": "2026-04-18",
    "purchaseCost": 128.77,
    "revenue": 206.86
  },
  {
    "date": "2026-04-19",
    "purchaseCost": 240.16,
    "revenue": 367.71
  },
  {
    "date": "2026-04-20",
    "purchaseCost": 18.15,
    "revenue": 30.93
  },
  {
    "date": "2026-04-21",
    "purchaseCost": 171.32,
    "revenue": 269.82
  },
  {
    "date": "2026-04-22",
    "purchaseCost": 100.19,
    "revenue": 179.85
  },
  {
    "date": "2026-04-23",
    "purchaseCost": 49.09,
    "revenue": 80.72
  },
  {
    "date": "2026-04-25",
    "purchaseCost": 100.28,
    "revenue": 149.18
  },
  {
    "date": "2026-04-26",
    "purchaseCost": 175.19,
    "revenue": 287.87
  },
  {
    "date": "2026-04-27",
    "purchaseCost": 126.77,
    "revenue": 210.48
  },
  {
    "date": "2026-04-28",
    "purchaseCost": 51.77,
    "revenue": 85.94
  },
  {
    "date": "2026-04-29",
    "purchaseCost": 59.55,
    "revenue": 99.48
  },
  {
    "date": "2026-04-30",
    "purchaseCost": 54.19,
    "revenue": 82.06
  },
  {
    "date": "2026-05-01",
    "purchaseCost": 21.8,
    "revenue": 40.2
  },
  {
    "date": "2026-05-02",
    "purchaseCost": 141.91,
    "revenue": 239.21
  },
  {
    "date": "2026-05-03",
    "purchaseCost": 245.43,
    "revenue": 398.8
  },
  {
    "date": "2026-05-04",
    "purchaseCost": 35.06,
    "revenue": 67.37
  },
  {
    "date": "2026-05-05",
    "purchaseCost": 123.15,
    "revenue": 205.27
  },
  {
    "date": "2026-05-06",
    "purchaseCost": 79.1,
    "revenue": 132.63
  },
  {
    "date": "2026-05-07",
    "purchaseCost": 169.77,
    "revenue": 277.44
  },
  {
    "date": "2026-05-08",
    "purchaseCost": 57.1,
    "revenue": 103.52
  },
  {
    "date": "2026-05-10",
    "purchaseCost": 93.01,
    "revenue": 153.49
  },
  {
    "date": "2026-05-11",
    "purchaseCost": 186.06,
    "revenue": 294.98
  },
  {
    "date": "2026-05-12",
    "purchaseCost": 126.69,
    "revenue": 206.4
  },
  {
    "date": "2026-05-13",
    "purchaseCost": 105.51,
    "revenue": 160.01
  },
  {
    "date": "2026-05-14",
    "purchaseCost": 86.96,
    "revenue": 138.95
  },
  {
    "date": "2026-05-15",
    "purchaseCost": 54.4,
    "revenue": 80.21
  },
  {
    "date": "2026-05-16",
    "purchaseCost": 98.63,
    "revenue": 160.94
  },
  {
    "date": "2026-05-17",
    "purchaseCost": 125.15,
    "revenue": 210.58
  },
  {
    "date": "2026-05-18",
    "purchaseCost": 123.62,
    "revenue": 197.79
  }
];
