// Auto-generated by scripts/updateData.js — last update: 2026-05-20
// CZ: per-order product basket value bez DPH (CZK), cancelled excluded
// One record per order. Use to build AOV histograms / distribution analysis.

export interface OrderValueRecord {
  date: string;   // ISO "2025-05-25"
  value: number;  // order basket value bez DPH (excl. shipping & payment)
}

export const orderValueDataCZ: OrderValueRecord[] = [];
