// Auto-generated by scripts/updateData.js — last update: 2026-05-20
// SK: product sales (cancelled/returned excluded)

export interface ProductSaleRecord {
  date: string;
  name: string;
  amount: number;
  revenue_vat: number;
  revenue: number;
}

export const productDataSK: ProductSaleRecord[] = [];
