// Auto-generated by scripts/updateData.js — last update: 2026-05-20
// CZ: per-customer retention data (CZK)

export const retentionDataCZ: { dates: string[]; revenues: number[]; revsVat: number[] }[] = [];
