// Auto-generated by scripts/updateData.js — last update: 2026-05-20
// SK: what customers paid for shipping & payment (EUR, cancelled excluded)

export interface ShippingPaymentRecord {
  date: string;         // ISO "2025-05-25"
  type: 'shipping' | 'payment';
  name: string;         // normalized method name e.g. "Zásilkovna", "Online platba kartou"
  count: number;        // number of orders using this method on this day
  free_count: number;   // orders where customer paid 0 (free shipping/payment)
  revenue_vat: number;  // total paid by customers incl. VAT
}

export const shippingPaymentDataSK: ShippingPaymentRecord[] = [];
