// Auto-generated by scripts/updateData.js — last update: 2026-05-19
// CZ: stock levels per product (live from Google Sheets)

export interface StockRecord {
  code: string;
  name: string;
  stock: number;
}

export const stockDataCZ: StockRecord[] = [
  {
    "code": "1203",
    "name": "Dary země a moře",
    "stock": 0
  },
  {
    "code": "1202",
    "name": "Chutě, které přineslo slunce",
    "stock": 21
  },
  {
    "code": "1126",
    "name": "Krémová pomazánka z lososa s estragonem 60 g",
    "stock": 25
  },
  {
    "code": "1107",
    "name": "Makrela Diablesse 112,5 g",
    "stock": 0
  },
  {
    "code": "1102",
    "name": "Makrela s hořčicí 112,5 g",
    "stock": 25
  },
  {
    "code": "1105",
    "name": "Makrela s kari kořením a mandlemi 112,5 g",
    "stock": 0
  },
  {
    "code": "1112",
    "name": "Makrela s omáčkou z bergamotu a kopru 118 g",
    "stock": 0
  },
  {
    "code": "1104",
    "name": "Makrela s rajčaty 112,5 g",
    "stock": 0
  },
  {
    "code": "1110",
    "name": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
    "stock": 0
  },
  {
    "code": "1100",
    "name": "Makrela ve víně s aromatickým kořením 118 g",
    "stock": 13
  },
  {
    "code": "1220",
    "name": "Makrelová eskapáda",
    "stock": 0
  },
  {
    "code": "1240",
    "name": "Malá mořeplavba",
    "stock": 0
  },
  {
    "code": "1200",
    "name": "Na objevitelské vlně",
    "stock": 0
  },
  {
    "code": "1125",
    "name": "Pěnová pomazánka z humra a koňaku 60 g",
    "stock": 27
  },
  {
    "code": "1127",
    "name": "Pomazánka z makrely s limetkou 60 g",
    "stock": 0
  },
  {
    "code": "1130",
    "name": "Pomazánka z tuňáka s parmezánem 60 g",
    "stock": 14
  },
  {
    "code": "1120",
    "name": "Pomazánka ze sardinek a whisky 60 g",
    "stock": 37
  },
  {
    "code": "1204",
    "name": "Rajská zahrada",
    "stock": 18
  },
  {
    "code": "1135",
    "name": "Rillettes z tresky se sečuánským pepřem 60 g",
    "stock": 20
  },
  {
    "code": "1040",
    "name": "Royanské sardinky s omáčkou Ravigote 115 g",
    "stock": 23
  },
  {
    "code": "1194",
    "name": "Salát z makrely s mrkví a čočkou Beluga 175 g",
    "stock": 0
  },
  {
    "code": "1193",
    "name": "Salát z tuňáka s paprikami a černou rýží 175 g",
    "stock": 20
  },
  {
    "code": "1192",
    "name": "Salát z tuňáka s provensálskou zeleninou a sherry octem 175 g",
    "stock": 20
  },
  {
    "code": "1191",
    "name": "Salát z tuňáka s tajine zeleninou a quinoou 175 g",
    "stock": 26
  },
  {
    "code": "1190",
    "name": "Salát ze sledě s kapustou a rýží Camargue BIO 175 g",
    "stock": 0
  },
  {
    "code": "1049",
    "name": "Sardinky HOT FISH s papričkou Habanero 115 g",
    "stock": 0
  },
  {
    "code": "1041",
    "name": "Sardinky Luzienne 115 g",
    "stock": 0
  },
  {
    "code": "1039",
    "name": "Sardinky marinované ve víně Muscadet 115 g",
    "stock": 26
  },
  {
    "code": "1062",
    "name": "Sardinky Nantaise na konzumaci po tepelné úpravě 115 g",
    "stock": 33
  },
  {
    "code": "1043",
    "name": "Sardinky s citronem a chilli papričkami 115 g",
    "stock": 141
  },
  {
    "code": "1065",
    "name": "Sardinky s kandovaným citronem a koriandrem na konzumaci po tepelné úpravě 115 g",
    "stock": 31
  },
  {
    "code": "1066",
    "name": "Sardinky s máslem a pohankou na konzumaci po tepelné úpravě 115 g",
    "stock": 21
  },
  {
    "code": "1060",
    "name": "Sardinky s máslem na konzumaci po tepelné úpravě 115 g",
    "stock": 14
  },
  {
    "code": "1045",
    "name": "Sardinky s olivami z Nice 115 g",
    "stock": 20
  },
  {
    "code": "1044",
    "name": "Sardinky s olivovou tapenádou 115 g",
    "stock": 0
  },
  {
    "code": "1033",
    "name": "Sardinky s olivovým olejem a citronem 115 g",
    "stock": 120
  },
  {
    "code": "1038",
    "name": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
    "stock": 128
  },
  {
    "code": "1064",
    "name": "Sardinky s orientálním kořením na konzumaci po tepelné úpravě 115 g",
    "stock": 16
  },
  {
    "code": "1047",
    "name": "Sardinky s pepřem Batak a kurkumou 115 g",
    "stock": 41
  },
  {
    "code": "1050",
    "name": "Sardinky s pepřem ze Sao Tome",
    "stock": 0
  },
  {
    "code": "1063",
    "name": "Sardinky s rajčaty a pistou na konzumaci po tepelné úpravě 115 g",
    "stock": 21
  },
  {
    "code": "1048",
    "name": "Sardinky se zeleným pepřem a kumquatem 115 g",
    "stock": 49
  },
  {
    "code": "1031",
    "name": "Sardinky sv. Jiří v olivovém oleji 115 g",
    "stock": 72
  },
  {
    "code": "1030",
    "name": "Sardinky v arašídovém oleji 115 g",
    "stock": 48
  },
  {
    "code": "1037",
    "name": "Sardinky v arašídovém oleji s citronem 115 g",
    "stock": 27
  },
  {
    "code": "1036",
    "name": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
    "stock": 17
  },
  {
    "code": "1035",
    "name": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
    "stock": 31
  },
  {
    "code": "1042",
    "name": "Sardinky v olivovém oleji s rajčaty 115 g",
    "stock": 203
  },
  {
    "code": "1046",
    "name": "Sardinky v olivovém oleji s timutským pepřem 115 g",
    "stock": 11
  },
  {
    "code": "1032",
    "name": "Sardinky v slunečnicovém oleji 115 g",
    "stock": 112
  },
  {
    "code": "1034",
    "name": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
    "stock": 32
  },
  {
    "code": "1004",
    "name": "Tuňák v olivovém oleji 160 g",
    "stock": 73
  },
  {
    "code": "1006",
    "name": "Tuňák v olivovém oleji s aromatickým kořením 160 g",
    "stock": 10
  },
  {
    "code": "1007",
    "name": "Tuňák v olivovém oleji s česnekem 160 g",
    "stock": 18
  },
  {
    "code": "1005",
    "name": "Tuňák v olivovém oleji se zeleným pepřem 160 g",
    "stock": 18
  },
  {
    "code": "1003",
    "name": "Tuňák ve vlastní šťávě 207 g",
    "stock": 12
  },
  {
    "code": "1230",
    "name": "Tuňáková revoluce",
    "stock": 10
  },
  {
    "code": "1241",
    "name": "Velká mořeplavba",
    "stock": 0
  },
  {
    "code": "1205",
    "name": "Vůně francouzské kuchyně",
    "stock": 14
  },
  {
    "code": "1201",
    "name": "Z rybářské sítě",
    "stock": 0
  }
];
