// Auto-generated by scripts/updateData.js — last update: 2026-05-20
// SK: stock levels per product (live from Google Sheets)

export interface StockRecord {
  code: string;
  name: string;
  stock: number;
}

export const stockDataSK: StockRecord[] = [
  {
    "code": "1203",
    "name": "Dary zeme a mora",
    "stock": 40
  },
  {
    "code": "1202",
    "name": "Chute, ktoré prinieslo slnko",
    "stock": 36
  },
  {
    "code": "1126",
    "name": "Krémová nátierka z lososa s estragónom 60 g",
    "stock": 36
  },
  {
    "code": "1107",
    "name": "Makrela Diablesse 112,5 g",
    "stock": 13
  },
  {
    "code": "1102",
    "name": "Makrela s horčicou 112,5 g",
    "stock": 55
  },
  {
    "code": "1105",
    "name": "Makrela s kari korením a mandľami 112,5 g",
    "stock": 12
  },
  {
    "code": "1112",
    "name": "Makrela s omáčkou z bergamotu a kôpru 118 g",
    "stock": 0
  },
  {
    "code": "1104",
    "name": "Makrela s paradajkami 112,5 g",
    "stock": 0
  },
  {
    "code": "1110",
    "name": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
    "stock": 0
  },
  {
    "code": "1100",
    "name": "Makrela vo víne s aromatickým korením 118 g",
    "stock": 39
  },
  {
    "code": "1220",
    "name": "Makrelová eskapáda",
    "stock": 0
  },
  {
    "code": "1240",
    "name": "Malá moreplavba",
    "stock": 0
  },
  {
    "code": "1200",
    "name": "Na objaviteľskej vlne",
    "stock": 2
  },
  {
    "code": "1127",
    "name": "Nátierka z makrely s limetkou 60 g",
    "stock": 6
  },
  {
    "code": "1130",
    "name": "Nátierka z tuniaka s parmezánom 60 g",
    "stock": 38
  },
  {
    "code": "1120",
    "name": "Nátierka zo sardiniek s whisky 60 g",
    "stock": 16
  },
  {
    "code": "1125",
    "name": "Penová nátierka z homára s koňakom 60 g",
    "stock": 34
  },
  {
    "code": "1204",
    "name": "Rajská záhrada",
    "stock": 40
  },
  {
    "code": "1135",
    "name": "Rillettes z tresky so sečuánskym korením 60 g",
    "stock": 31
  },
  {
    "code": "1040",
    "name": "Royanské sardinky s omáčkou Ravigote 115 g",
    "stock": 55
  },
  {
    "code": "1041",
    "name": "Sardinky Luzienne 115 g",
    "stock": 52
  },
  {
    "code": "1039",
    "name": "Sardinky marinované vínom Muscadet 115 g",
    "stock": 77
  },
  {
    "code": "1062",
    "name": "Sardinky Nantaise na konzumáciu po tepelnej úprave 115 g",
    "stock": 21
  },
  {
    "code": "1047",
    "name": "Sardinky s batackým korením a kurkumou 115 g",
    "stock": 25
  },
  {
    "code": "1043",
    "name": "Sardinky s citrónom a čili papričkami 115 g",
    "stock": 64
  },
  {
    "code": "1065",
    "name": "Sardinky s kandizovaným citrónom a koriandrom na konzumáciu po tepelnej úprave 115 g",
    "stock": 14
  },
  {
    "code": "1066",
    "name": "Sardinky s maslom a pohánkou na konzumáciu po tepelnej úprave 115 g",
    "stock": 7
  },
  {
    "code": "1060",
    "name": "Sardinky s maslom na konzumáciu po tepelnej úprave 115 g",
    "stock": 25
  },
  {
    "code": "1045",
    "name": "Sardinky s olivami z Nice 115 g",
    "stock": 36
  },
  {
    "code": "1044",
    "name": "Sardinky s olivovou tapenádou 115 g",
    "stock": 68
  },
  {
    "code": "1033",
    "name": "Sardinky s olivovým olejom a citrónom 115 g",
    "stock": 0
  },
  {
    "code": "1038",
    "name": "Sardinky s olivovým olejom a zeleným korením 115 g",
    "stock": 116
  },
  {
    "code": "1064",
    "name": "Sardinky s orientálnym korením na konzumáciu po tepelnej úprave 115 g",
    "stock": 12
  },
  {
    "code": "1063",
    "name": "Sardinky s paradajkami a pistou na konzumáciu po tepelnej úprave 115 g",
    "stock": 21
  },
  {
    "code": "1048",
    "name": "Sardinky so zeleným korením a kumkvatom 115 g",
    "stock": 34
  },
  {
    "code": "1031",
    "name": "Sardinky sv. Juraja v olivovom oleji 115 g",
    "stock": 620
  },
  {
    "code": "1030",
    "name": "Sardinky v arašidovom oleji 115 g",
    "stock": 47
  },
  {
    "code": "1037",
    "name": "Sardinky v arašidovom oleji s citrónom 115 g",
    "stock": 47
  },
  {
    "code": "1036",
    "name": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
    "stock": 52
  },
  {
    "code": "1035",
    "name": "Sardinky v olivovom oleji s aromatickým korením 115 g",
    "stock": 59
  },
  {
    "code": "1042",
    "name": "Sardinky v olivovom oleji s paradajkami 115 g",
    "stock": 187
  },
  {
    "code": "1046",
    "name": "Sardinky v olivovom oleji s timutským korením 115 g",
    "stock": 30
  },
  {
    "code": "1032",
    "name": "Sardinky v slnečnicovom oleji 115 g",
    "stock": 88
  },
  {
    "code": "1034",
    "name": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
    "stock": 40
  },
  {
    "code": "1194",
    "name": "Šalát z makrely s mrkvou a šošovicou beluga 175 g",
    "stock": 50
  },
  {
    "code": "1193",
    "name": "Šalát z tuniaka s jednozrnkou a čiernou ryžou 175 g",
    "stock": 27
  },
  {
    "code": "1192",
    "name": "Šalát z tuniaka s provensálskou zeleninou a sherry octom 175 g",
    "stock": 25
  },
  {
    "code": "1191",
    "name": "Šalát z tuniaka so zeleninou tajine a quinoou 175 g",
    "stock": 28
  },
  {
    "code": "1190",
    "name": "Šalát zo sleďa s kelom a ryžou z Camargue BIO 175 g",
    "stock": 5
  },
  {
    "code": "1004",
    "name": "Tuniak v olivovom oleji 160 g",
    "stock": 50
  },
  {
    "code": "1006",
    "name": "Tuniak v olivovom oleji s aromatickým korením 160 g",
    "stock": 21
  },
  {
    "code": "1007",
    "name": "Tuniak v olivovom oleji s cesnakom 160 g",
    "stock": 39
  },
  {
    "code": "1005",
    "name": "Tuniak v olivovom oleji so zeleným korením 160 g",
    "stock": 34
  },
  {
    "code": "1003",
    "name": "Tuniak vo vlastnej šťave 207 g",
    "stock": 50
  },
  {
    "code": "1230",
    "name": "Tuniaková revolúcia",
    "stock": 21
  },
  {
    "code": "1241",
    "name": "Veľká moreplavba",
    "stock": 21
  },
  {
    "code": "1205",
    "name": "Vôňa francúzskej kuchyne",
    "stock": 9
  },
  {
    "code": "1201",
    "name": "Z rybárskej siete",
    "stock": 30
  }
];
